### PR TITLE
Outer Rim Patches pt3: Dungeons & Droids

### PR DESCRIPTION
**Pull request by Arcalane**
## Additions

ROUND THREE. Now partially supporting Turrets, Droid Depot, and Vambraces! This mainly covers droid equipment and some other assorted gubbins.

The AI is, thankfully, smart enough to use the mounted weapons to engage at range. The droid-mounted weapons are extremely accurate with a clear line of fire, but currently have pretty slow rates of fire. Still, I wouldn't want to be on the wrong end of an SBD's rocket launcher.

## Changes

- Supports all droid-mounted weapons, armours, and the droid jetpack. Basic, ion, and twin blasters fire rifle-grade shots (standard/ion), whilst the cannon fires AP sniper shots and the wrist rocket has a new ammo type. They reload with appropriate ammo types at appropriate rates.
- Armours are intended to be comparable to light/medium/heavy infantry tiers, but offer 100% protection to all locations due to the way equipping them works at the moment, making them slightly better than personnel armour. They're stuffable and can get quality bonuses, so high-quality plasteel droid armour is pretty dang tough!
- Droid components don't seem to benefit from reduced bulk when equipped, or grant bulk cap increases, hence their identical, low bulk/wornbulk values.
- Made some of the Imperial and other faction weapons a little more flavourful by adjusting the stats a bit more, mostly in terms of range/capacity/cooldown/accuracy.
- Figured out where the vanilla accuracy values were being set and removed them from all weapons. I don't think this actually does anything, it just hides them from weapon info cards and aiming calculations.
- Added partial support for vambraces. Currently only the tranq vambrace; flamer/cryoban are untouched and still use their old logic. The whipcord vambrace is untouched (I considered adding capacity and a durasteel refuel cost, but decided against it in the end).
- Added minirockets and tranquilizer darts as buildable ammos, currently only used by the droid wrist rocket and knockout dart vambrace respectively. This seems to cause some weirdness with storage categories since they're not tied to actual weapons though.
- Fixed the chargenoun for all grenade belts being "frag(s)" because that was bothering me.
- Patched armour values on Republic kamas (leg guards) as intended in the last patch.
- Patched humanoid droids with various base features. Only tactical and supertac droids have the suppression comp added. Most droids have fairly basic melee attacks, except SBDs which have really nasty (relatively speaking) punch attacks.
- Turrets are finally patched, using tibanna fuel with CE-compatible verbs and projectiles. Their fillPercent has been increased so they can shoot past sandbags and through embrasures. Their general range accuracy values are unchanged, so they're very nasty against exposed pawns at shorter ranges, but the smaller turrets are outranged by CE's longer-ranged assault weapons, and they still suffer against targets in good cover. Turret projectile damage/pen values are quick and dirty, using rifle bolts as the baseline and doubling each step for medium/large, probably need tuning.
- Small turrets have been made placeable under roofs, and non-artillery turrets have all been given radius placeworkers so you can see their maximum (and minimum, if applicable) ranges.
- Rebalances most standard weapons for more consistent warmup, cooldown, range, capacity, sway, spread, sight efficiency, fire rate/burst mode, *etc.* stats.

## Current Un-pushed Changes
- None!

## Notable Issues

Due to the way icons are handled for projectile-launching verbs on accessories, the flamer and cryoban vambraces aren't currently patched with a reload system. There doesn't seem to be a convenient or obvious way to override with `icon` or `iconPath` for... some reason, unfortunately. I would *like* to get this solved before this round is merged, but worst come to worst they can be left as-is (right now they have infinite uses with an outrageously long cooldown of ~12 ingame hours or something).

They work fine if the projectile uses a simple static sprite, but due to the flamer/cryoban bracers using a fancy fwooshy VWE-style animated effect the system will complain about null references at the moment. I could just fuck around with making them work like regular CE flamers (and figure out something else for the cryoban) but that'll be a lot of effort as well.

I'm not sure if player-owned B2s can fire their wrist guns independently of player control, making them rather micro-heavy. (Though the wrist-rocket is manual-only on purpose.)

## Testing

- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (this is (partially) the result of actual live playtesting and number-crunching)

### CODE REVIEW

**Comment by Arcalane** [comment]
Now working on turret patches. I figured out how to make them retain the tibanna fuelling whilst still using CE-compatible verbs and projectiles.

**Comment by Maeyanie** [comment]
Thanks for making these patches.

As a note, I haven't tried your latest version here yet so I'm not sure if this has been changed, but most Star Wars weapons are semi-auto only... not sure if having them all full-auto is intentional for balance reasons, but it feels kind of weird.

**Comment by Arcalane** [comment]
> Thanks for making these patches.

Honestly it wasn't as hard as I thought it'd be, once I got over the initial hurdles of ammo not spawning and console feedback being unhelpful. Just annoying that I've apparently chosen to get it all done in the month or two before Anomaly releases. Oh well, not like I could have known that was coming when I started.

> As a note, I haven't tried your latest version here yet so I'm not sure if this has been changed, but most Star Wars weapons are semi-auto only... not sure if having them all full-auto is intentional for balance reasons, but it feels kind of weird.

Rates of fire are largely untouched from Neronix' baseline implementation, save for some adjustments to the heavier weapons and additions of intermediate burst modes.

Consider it a balance/gameplay thing. The projectile stats and range/accuracy values on guns are more or less 1:1 with charge weapons (save that blasters have atrociously low levels of blunt pen), so most blasters being semi-only would put them at an immediate disadvantage against any other charge-tier weapons.

**Comment by Maeyanie** [comment]
> Consider it a balance/gameplay thing. The projectile stats and range/accuracy values on guns are more or less 1:1 with charge weapons (save that blasters have atrociously low levels of blunt pen), so most blasters being semi-only would put them at an immediate disadvantage against any other charge-tier weapons.

Makes sense. Trying to rebalance them to still be useful when semi-auto would be a pain, so that does sound like the best approach. 👍

**Comment by Arcalane** [comment]
> Makes sense. Trying to rebalance them to still be useful when semi-auto would be a pain, so that does sound like the best approach. 👍

I figure it's an acceptable break that's still *somewhat* in-line with games anyway-- Dark Forces *et al.* portrayed the E-11 as having a rapid-fire mode, after all, and it's not like Star Wars has ever been consistent as a setting.

**Comment by Arcalane** [comment]
Redrafting pending a pass on weapon stats (sway, warmup, etc.). Will probably also include any necessary changes for the loadfolders migration when the time comes.

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
