### PR TITLE
More shell types for Artillery Foundry (VFE: Mechanoids)

### PR DESCRIPTION
**Pull request by amaotoUsagi**
## Additions

Added/Changed it to a PatchOperationFindMod so that any of said mods could activate the recipe
Added Support for:
60mm, 90mm Gun
76.2mm Gun
 - WWII Soviet Pack
 - VFE:Pirates
105mm
 - Combat Extended: Guns
155mm
 - Fortifications: Industrial
 - TMC Weapon Pack
 - Turret Collection
 - VFE: Security

## Reasoning

- To prevent the factory from producing unneeded ammo on its own, I made the recipes require their specific mods
- as jakeytankey#9691 said, It would make sense for the factories to make ammunition for VE stuff. Considering that you can make Mechanoid ammo in the Foundry as well, I decided to add the 60mm as well
- since the comments said that the factories are finicky with its inputs, I followed the same reason for the 105mm and 155mm EMP shell to use 20 chemfuel and subtracting 2 components to their cost

## Alternatives

- I did try to make it not require the mods, but it would end up being able produce 105mm/155mm without any weapon/turret that uses it.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by Safairette** [comment]
Could be neat to still keep 105mm shells even with the Field Gun changes, since the CE guns Howitzer still uses 105mm

**Comment by ItsSamGray** [comment]
Yea, the 105mm shells should be kept with a CE guns dependency and add another one for the 76.2mm shell

**Comment by amaotoUsagi** [comment]
ahhh crap I forgot to remove the (currently commented out) in the description but its actually ready lol

**Review by ItsSamGray — APPROVED** [review]
LGTM

**Pull request merged**
