### PR TITLE
Patch Vanilla Vehicles Expanded

### PR DESCRIPTION
**Pull request by SamaelGray**
## Additions

- Patch the vehicles in Vanilla Vehicles Expanded.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by T-rexsuper1** [comment]
Class="PatchOperationReplace">
					<xpath>Defs/Vehicles.VehicleTurretDef[defName="Tango_MainTurret"]/ammunition/thingDefs</xpath>
is wrong. Yours uses Bullet_[caliber] when it should be Ammo_[caliber]. Changed, tested, it works.

**Comment by JulekJulas** [comment]
The latest assembly is 22 bytes and without any folders

**Comment by SamaelGray** [comment]
> Class="PatchOperationReplace"> Defs/Vehicles.VehicleTurretDef[defName="Tango_MainTurret"]/ammunition/thingDefs is wrong. Yours uses Bullet_[caliber] when it should be Ammo_[caliber]. Changed, tested, it works.

Did you manage to make the turrets actually fire or not?

**Comment by T-rexsuper1** [comment]
> > Class="PatchOperationReplace"> Defs/Vehicles.VehicleTurretDef[defName="Tango_MainTurret"]/ammunition/thingDefs is wrong. Yours uses Bullet_[caliber] when it should be Ammo_[caliber]. Changed, tested, it works.
> 
> Did you manage to get the turrets to actually fire or not?

They did fire

**Comment by SamaelGray** [comment]
> > > Class="PatchOperationReplace"> Defs/Vehicles.VehicleTurretDef[defName="Tango_MainTurret"]/ammunition/thingDefs is wrong. Yours uses Bullet_[caliber] when it should be Ammo_[caliber]. Changed, tested, it works.
> > 
> > 
> > Did you manage to get the turrets to actually fire or not?
> 
> They did fire

Then I need the patches you used your the mod list, post the patches in a pastebin link or something please.

**Comment by T-rexsuper1** [comment]
> > > > Class="PatchOperationReplace"> Defs/Vehicles.VehicleTurretDef[defName="Tango_MainTurret"]/ammunition/thingDefs is wrong. Yours uses Bullet_[caliber] when it should be Ammo_[caliber]. Changed, tested, it works.
> > > 
> > > 
> > > Did you manage to get the turrets to actually fire or not?
> > 
> > 
> > They did fire
> 
> Then I need the patches you used and your mod list, post the patches in a pastebin link or something please.

Discord DMs, sent.

**Comment by Igoptt** [comment]
Heyo, changing the `genericAmmo` to true makes it so the vehicles can fire their weapons, this does however make them restricted to only one ammo type

**Comment by T-rexsuper1** [comment]
> github

Feedback with this one. 
Ammo type selection now works. But the guns stopped firing

**Review by Thorbane — DISMISSED** [review]

**Review by Thorbane — DISMISSED** [review]

**Review by Thorbane — APPROVED** [review]

**Comment by T-rexsuper1** [comment]
Needs further testing, took me 21 shots from 75mm bulldog cannon to destroy a Tango. That's not how any vehicles work, and that's definitely now how CE balance works.

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
