### PR TITLE
Caulaflower Explosives expansion

### PR DESCRIPTION
**Pull request by Caulaflower**
## Additions

Adds a new option to make rockets explode after hitting a wall

Added a mechanic for mostly mechs where hitting a specified organ can detonate carried ammo

## Changes

When a projectile with the bunkerbuster thingclass hits a wall it will explode behind it. How much behind it depends on stats in rpg-7 example

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

### CODE REVIEW

**Review by ItsSamGray — DISMISSED** [review]
Looks good to me and working as intended

**Comment by N7Huntsman** [comment]
Don't merge this as of just yet. I'd both like to see it tested more thoroughly, and for there to be the opportunity to compare notes with some of the other penetration stuff that's been attempted.

**Comment by Caulaflower** [comment]
> Don't merge this as of just yet. I'd both like to see it tested more thoroughly, and for there to be the opportunity to compare notes with some of the other penetration stuff that's been attempted.

This is quite a different thing to the other penetration mechanics like in CE effects or Karim's old stuff, it's not possible to make a non explosive bullet penetrate through stuff with this, all this does it make the explosion on the calculated tile

**Review by N7Huntsman — APPROVED** [review]

**Review by N7Huntsman — APPROVED** [review]

**Review by ItsSamGray — DISMISSED** [review]

**Review by ItsSamGray — APPROVED** [review]
Working as intended

**Pull request merged**
