### PR TITLE
Nanosuit

### PR DESCRIPTION
**Pull request by Breadbox2k19**
Maximum Power

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Review by N7Huntsman — COMMENTED** [review]
The helmet seems fine, but several of the operations for the suit itself are failing because the target is contained within `@Name="ApparelArmorNanoSuitBase"`.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
Nanosuit needs looked at. It uses multiple bases that have some of those stats.

**Comment by Breadbox2k19** [comment]
would require further tweak for the night vision.

**Comment by Breadbox2k19** [comment]
think i'll hold on merging this, nanosuit doesn't even work in vanilla.

**Comment by Breadbox2k19** [comment]
Ready to go, the power mode still doesn't work in CE tho.

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
