### PR TITLE
Railgun ammo rebalanced

### PR DESCRIPTION
**Pull request by SamaelGray**
## Changes

- What it says on the tin, made the ammo more useable in handheld weapons.

## References

- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit#gid=1393347070

## Reasoning

- 6mm ammo for pistol and SMGs, 8mm ammo for rifles and 12mm ammo for AMRs and bigger weapons.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

### CODE REVIEW

**Review by SerinaCE — APPROVED** [review]

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
Holding this PR til the load folders migration is complete to prevent creating conflicts.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
While I'm on board with the recipe changes of adding chemfuel, I disagree with the projectiles stat changes being proposed.

If we want lower velocity versions of the projectiles, then just make a LV version of the round--but as it stands, the projectiles have their own roles they're stat'd for.

12mm is a heavy, turret mounted railgun round. 8mm is roughly a spacer anti-material rifle caliber. 6mm is a full-powered rifle round.

**Comment by SamaelGray** [comment]
> While I'm on board with the recipe changes of adding chemfuel, I disagree with the projectiles stat changes being proposed.
> 
> If we want lower velocity versions of the projectiles, then just make a LV version of the round--but as it stands, the projectiles have their own roles they're stat'd for.
> 
> 12mm is a heavy, turret mounted railgun round. 8mm is roughly a spacer anti-material rifle caliber. 6mm is a full-powered rifle round.

Counterpoint. none of the existing ammo type make sense in a handheld human useable weapon hence them not being used anywhere and 8mm rounds are weaker than 6mm ones by all means so the role described here is not reflective of the stats.

**Comment by N7Huntsman** [comment]
12mm is being used as intended in around a dozen heavy railgun turrets/weapons, and a few very heavy Ultratech weapons.

I misspoke on the 8mm, since it's described as being for "railgun pistols". That one we could slow down a touch, but that'll also require making a pass through the patches and swapping it out for 6mm in a lot of cases. At present, it's being used as the railgun equivalent to a full-power rifle cartridge in about two dozen patches, which I'd chiefly attribute that to it having too much damage/velocity for the railgun pistol role.

6mm is being used as-intended in about half-a-dozen patches and, as noted above, should be used more widely in cases where 8mm as currently in-use.

**Comment by SamaelGray** [comment]
In that case, I'm going to close this PR as it's clearly requiring discussion over the design intent and how it can be modified and rebalanced which I simply don't have access to such an appropriate discussion medium required for it.

**Pull request closed without merging**
