### PR TITLE
Unnecessary animal body size patches removal

### PR DESCRIPTION
**Pull request by ItsSamGray**
## Changes

- A redo of the #1558 PR with proper melee stat changes.

## References

- The new spreadsheet can be found here:
https://docs.google.com/spreadsheets/d/1_DoUk2MZmS44m8ivtSfhSMZQchVZHNS6VLcSwW0O1ps/edit#gid=1020770989

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors

### CODE REVIEW

**Review by albertbokor — APPROVED** [review]
LGTM!

**Comment by Breadbox2k19** [comment]
Why on earth are you touching the fucking alpha animal patch for no reason? I spent countless hours actually testing and balancing animal patches for almost update for years at this point, every bodysize tweak or "inconsistency" is an intentional balancing choice from hours of testing in CE. Do you even have the slightest idea why you are doing this other than being consistent?

**Comment by albertbokor** [comment]
The reversing chagest o core was my idea.
Some values looked just very wierd and unnecessary like halving the size of dromedaries (consequently fucking up their carry weight for no other benefit) and setting them slower than pawns.

**Comment by albertbokor** [comment]
> Why on earth are you changing the alpha animal patch for no reason? I spent countless hours actually testing and balancing animal patches for almost every update for years at this point from the very first iteration, every bodysize tweak, pain threshold or "inconsistency" is an intentional balancing choice from hours of testing in CE. You not understanding why its there doesn't mean it's unneccessary. Do you even have the slightest idea why you are doing this other than being "consistent"?
> I'm not the one who is undoing hours upon hours of works and testing, you are, you are making the patches worse for literally no reason.

The reversing chagest o core was my idea.
Some values looked just very wierd and unnecessary like halving the size of dromedaries (consequently fucking up their carry weight for no other benefit) and setting them slower than pawns.
Tho ye, agree on not to fuck with Alpha Animals.

**Comment by ItsSamGray** [comment]
> Why on earth are you changing the alpha animal patch for no reason? I spent countless hours actually testing and balancing animal patches for almost every update for years at this point from the very first iteration, every bodysize tweak, pain threshold or "inconsistency" is an intentional balancing choice from hours of testing in CE. You not understanding why its there doesn't mean it's unneccessary. Do you even have the slightest idea why you are doing this other than being "consistent"?
> 
> I'm not the one who is undoing hours upon hours of works and testing, you are, you are making the patches worse for literally no reason.

The current change to AA animals are for only 3 animals which are receiving a buff, also the previous changes to AA stuff had very good balancing reason which all were discussed over on discord. I don't go ahead and break the patch of a mod that I personally enjoy.
None of the patches are undone and made worse. Mind you that these changes are made because changing basebodysize stat currently does nothing but lowering the carry capacity and melee chance stats, the hitboxes of the pawns which were previously affected by their body size are only decided by their actual in-game texture and nothing else.

**Review by albertbokor — APPROVED** [review]
LGTM!

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
