### PR TITLE
Rimworld of Magic Compatibility patch

### PR DESCRIPTION
**Pull request by Person243546**
## Additions

Patches Rimworld of Magic to work with CE.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by Lion-ion** [comment]
I've been testing this for a few days. All(that I tested)) of the direct effect/direct damage spells abilities work correctly, but there are a few notable ones that fail to work--the psionic barrier for instance doesn't register the projectiles from CE. I'm guessing it's something that you can't patch through xml?

**Comment by perkinslr** [comment]
> I've been testing this for a few days. All(that I tested)) of the direct effect/direct damage spells abilities work correctly, but there are a few notable ones that fail to work--the psionic barrier for instance doesn't register the projectiles from CE. I'm guessing it's something that you can't patch through xml?

That is correct.  How is the psionic barrier supposed to work?  Is it (partial) immunity for the pawn struck?  Or does it provide a "field" around them (or at some other location on the map)?  Generally adding support for new types of shields is easy, but does take a bit of C# code.

**Comment by Person243546** [comment]
The only other class I found to be broken with CE is the super soldier. The super soldier also needed C# knowledge to work.

**Comment by Breadbox2k19** [comment]
Thank you, searching high and low for this.

**Comment by Lion-ion** [comment]
>
> That is correct. How is the psionic barrier supposed to work? Is it (partial) immunity for the pawn struck? Or does it provide a "field" around them (or at some other location on the map)? Generally adding support for new types of shields is easy, but does take a bit of C# code.

Depending on the ability's level, they can project a round barrier of varying sizes (also dependent on the level) onto themselves or a target location. On hit, it drains the pawn's mental resource(psionic energy and/or stamina).

I have a reasonable suspicion there are a few more abilities like this, and I'll report whenever they come up.

**Comment by Breadbox2k19** [comment]
Slightly off-topic here, how is it that your fork of Combat Extended contains the Zeta reticulan patch but the main development build doesn't?

**Comment by Person243546** [comment]
I have no idea. Maybe it was removed?

**Comment by sumghai** [comment]
@Breadbox2k19 @Person243546 - It seems that the Zeta Reticulan patches were indeed removed:

https://github.com/CombatExtended-Continued/CombatExtended/commit/5c3225980645e1b05e74e8d0c27808c006d6e8ef

Personally, what I tend to do is to periodically fetch the latest state of the Dev build from the official repo, then force-push it to my fork via Git Shell commands, so that my fork is always exactly even with the upstream.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
- Lesser Wind Elemental needs patched.
- The magical rings, pendants, and amulets should probably have their Bulk set lower than the default 1.
- Some of the armors that can still be made of metals like Silver need to be addressed, since they're basically useless as armor.

**Comment by Breadbox2k19** [comment]
RWM got updated again, seems like it would require an additional update.

**Comment by Person243546** [comment]
I looked over the change log and the update seems to tweak existing classes while not adding anything incompatible with CE.

**Comment by Person243546** [comment]
I accidentally deleted the repository from my Github so I made another Pull request

**Pull request closed without merging**
