### PR TITLE
Add gizmo to order reloading worn armor (or other CompReloadable apparel)

### PR DESCRIPTION
**Pull request by perkinslr**
## Additions

Describe new functionality added by your code, e.g.
Allows ordering drafted colonists to reload their reloadable apparel

## Reasoning

Doing it this way hooks into the existing reload logic for apparel (when pawns are not drafted).

## Alternatives

Manually create the reload job (duplicates code)

## Testing

Check tests you have performed:
- [X] Compiles without warnings
- [X] Game runs without errors
- [X] (For compatibility patches) ...with and without patched mod loaded
- [X] Playtested a colony (royalty)

### CODE REVIEW

**Review by N7Huntsman — APPROVED** [review]
Does appear to work as intended. Would it be possible to grey out the reload button when the pawn is not carrying valid ammo, to match the integrated weapon gizmo, that greys-out when out of charges?

**Comment by perkinslr** [comment]
> Does appear to work as intended. Would it be possible to grey out the reload button when the pawn is not carrying valid ammo, to match the integrated weapon gizmo, that greys-out when out of charges?

Maybe, if I can crib the code to do it from the integrated weapon gizmo.  I likely won't have time to do it for the next couple weeks, so I think we should not worry about it for this PR, just open an issue for it so we don't forget.

**Comment by N7Huntsman** [comment]
> Maybe, if I can crib the code to do it from the integrated weapon gizmo. I likely won't have time to do it for the next couple weeks, so I think we should not worry about it for this PR, just open an issue for it so we don't forget.

Fair enough, it's not a serious concern. If a code review says this looks okay, I'm happy with it.

**Review by simplyWiri — DISMISSED** [review]
Not important but I noted it down anyway:
1. I do not believe the list of similar commands is needed or used, and the methods relating to it could be removed entirely (`GroupsWith`, `MergeWith`). 
2. A small nit-pick would be consistent spacing inside the lambda.

Regardless of whether the above changes are made, looks fine to me.

**Comment by perkinslr** [comment]
> Not important but I noted it down anyway:
> 
>     1. I do not believe the list of similar commands is needed or used, and the methods relating to it could be removed entirely (`GroupsWith`, `MergeWith`).
> 
>     2. A small nit-pick would be consistent spacing inside the lambda.
> 
> 
> Regardless of whether the above changes are made, looks fine to me.

Fixed the whitespace issue, still need to write a .clang-format for this...  As for `GroupsWith` and `MergeWith`, they determine how the gizmo behaves when you have a large group of pawns selected, without permission to merge, you'd have one gizmo per pawn with reloadable equipment.  That may be desirable given that you may not want to have *everyone* fire a grenade, but without the ability to see which gizmo goes to which pawn I don't think it's useful to keep them split.  At some point in the future, maybe the pawns name could get added to the gizmo label when in a group.

**Review by simplyWiri — DISMISSED** [review]

**Review by simplyWiri — APPROVED** [review]

**Pull request merged**
