### PR TITLE
Outer Rim Patches

### LINKED ISSUE #2479: [Patch Request]: Outer Rim - Core
**Mod name:** Outer Rim - Core

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2919227155

**Description:**
The core mod adds universal research, buildings, resource systems, materials, power, production, turrets, stuff that could be used by any other module as a crafting building or crafting ingredient. 

Note: the extension mods from the collection adds more than what is above^ like factions, new races, and creatures so I will only check the boxes that apply to the core mod; and make patch requests for each one of those mods separately unless told to do otherwise

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

Thanks for your time

### LINKED ISSUE #2482: [Patch Request]: Outer Rim - Galactic Empire
**Mod name:** Outer Rim - Galactic Empire

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2919248699

**Description:**
A module for the Outer Rim series of that primarily covers a new faction, including apparel, weapons, and research. Requires Outer Rim - Core

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [x] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

Thanks for your time

### LINKED ISSUE #2483: [Patch Request]: Outer Rim - Galactic Republic
**Mod name:** Outer Rim - Galactic Republic

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2971930101

**Description:**
A module for the Outer Rim series of that primarily covers a new faction, including apparel, weapons, and research. Requires Outer Rim - Core

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [x] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

Thanks for your time

### LINKED ISSUE #2484: [Patch Request]: Outer Rim - Mandalore
**Mod name:** Outer Rim - Mandalore

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2920516629

**Description:**
A module for the Outer Rim series of that primarily covers a new faction, including apparel, weapons, and research. Requires Outer Rim - Core

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [x] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

Thanks for your time

### LINKED ISSUE #2485: [Patch Request]: Outer Rim - Old Republic
**Mod name:** Outer Rim - Old Republic

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2926855407

**Description:**
A module for the Outer Rim series of that primarily covers a new faction, including apparel, weapons, and research. Requires Outer Rim - Core

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [x] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

Thanks for your time

### LINKED ISSUE #2486: [Patch Request]: Outer Rim - Rebel Alliance
**Mod name:** Outer Rim - Rebel Alliance

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2919249903

**Description:**
A module for the Outer Rim series of that primarily covers a new faction, including apparel, weapons, and research. Requires Outer Rim - Core

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [x] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

Thanks for your time

### LINKED ISSUE #2487: [Patch Request]: Outer Rim - Chiss Ascendancy
**Mod name:** Outer Rim - Chiss Ascendancy

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2919962538

**Description:**
A module for the Outer Rim series of that primarily covers a new faction, including apparel, weapons, and research. Requires Outer Rim - Core

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [x] New animals, humanoids, or other creatures.
- [x] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

Thanks for your time

### PR DESCRIPTION
**Pull request by Arcalane**
## Additions

This PR is intended to patch all of Neronix' current Outer Rim mods with full CE support. This PR ~~will remain as a draft until I'm satisfied that it's somewhat-ready to go. I am making reasonable progress now!~~ is now in a state where I feel confident that it's ready for actual review.

Most full-body suit values (_e.g._ stormtrooper, scout trooper) assume the wearer also has the Outer Rim Core durafiber bodysuit for the purposes of both toxic resistance and overall armour, with each piece (bodysuit, cuirass, helmet, pauldrons) offering 25% toxic resistance for a total of 100%. I am gunning for a full set of _normal_-quality armour _with bodysuit_ to offer around ~15mm RHA torso protection, and ideally blasters will perform around the same tier as current charge weapons. Heads/limbs receive ~80% of torso protection value, and hands/feet receive ~60%.

By comparison, blaster pistols can't reliably penetrate all-normal grade equipment on a torso hit but rifles should be able to fairly handily, and sniper rifles will do so quite easily. Pistols and snipers are low capacity (10~20), rifles are mid capacity (~50), and heavy rifles are very high capacity (200+). The Jedi Knight/Dark Forces series never included reloading as a concept, so I'm just kinda eyeballing it outside of cases where hard numbers *are* available (for instance due to the weapon appearing in games or other media like the DC-17m in Republic Commando).

## Notes / Reminders-to-self
- Basic Stormtrooper (and certain other) helmets no longer confer a shooting accuracy penalty as they do in the base mod, as funny as stormtrooper marksmanship jokes are.
- Training Hediffs on factions are untouched.
- ~~Need to add Strapped layer coverage to helmets (otherwise they permit Visage Masks and other facewears, which makes no sense and also looks goofy)~~ Done!
- ~~Now that the basic abstracts are all handled I need to go through on a per-item basis and tweak any outliers that have specific/overriding values or need special adjustments.~~ - Done most of the standouts here. A few cases of needing to override values due to uneven inheritance.
- Enclosed helmets grant 100% smoke resistance, open helmets (rebel, imperial army/cadet/SB, etc.) do not. Certain helmets (scout trooper, mandalorian, etc.) will offer some night vision efficiency. 
- Most everything requires hypertech components which are made using advanced components and durasteel, so it seems fair to have decent NV and smoke/tox protection on most gear.
- A lot of the current numbers are placeholders and constructive input on balancing is welcome, as are other contributions. This is my first major patch project for CE, so expect some rough edges. Most weapons are based off their Core or VWE closest-analogues.
- Mandalorian armour can go _much_ higher protection-wise, mostly because I wanted it to be authentic to the live-action series. The tradeoff here is that it heavily depends on the material you use to make it- so you need to use plasteel or beskar (or better yet pure beskar) and have a very high level crafter in order to get the best results.
- ~~Turrets could be tricksy, since I *think* they're fuelled by tibanna and can be hooked up to a tibanna pipe grid for this purpose rather than using specific loaded ammo like other turrets. But~~ I'm going to worry about these later. They can be a seperate PR if need be.
- Rebel Alliance faction pawns have lower armour values than other faction pawns due to their outfits not incorporating proper body armour. The upshot is they don't have the movespeed penalty that full cuirass pieces apply.
- It would be nice to have some unique ammo graphics, but I am no artist so these will have to wait. Standard charge ammo will do in the meantime.
- Vibroweapons have been made using the Royalty Monosword as a guideline, tweaked per weapon. For instance the double-blade has blazing fast attack speeds but is not very good on defense, whilst the glaive has the slowest attack speeds but also has good defense (particularly parry). Like the monosword they all have high crit chances.
- Some descriptions have been patch-replaced for greater clarity or to cut down on what feel like unnecessarily snarky or fourth-wall-breaking comments.
- The Galactic Republic and Rebel Alliance share rocket ammo, of which there is only one type, for simplicity's sake. I've justified this with some new description info explaining how the Republic's dissolution left many stockpiles of rockets that the Rebels found and took advantage of. The rocket itself is both powerful against single targets and has a small but potent blast area, with no fragments.

## References
- Resolves #2479 
- Resolves #2482
- Resolves #2483
- Resolves #2484
- Resolves #2485
- Resolves #2486
- Resolves #2487

## Progress/TODO
- [x] Core Armour/Apparel
- [x] Core Ammo Sets
- [x] Core Melee Weapons
- [x] Core Ranged Weapons
- [x] Core Grenades
- [x] Core Mines
- [x] Core Materials
- [x] Core Jetpacks (+ Addon Jetpacks)
- [x] Chiss Ascendancy Armour
- [x] Chiss Ascendancy Weapons
- [x] Galactic Empire Armour
- [x] Galactic Empire Weapons
- [x] Galactic Republic Armour
- [x] Galactic Republic Weapons
- [x] Mandalorian Armour
- [x] Mandalorian Melee Weapons
- [x] Mandalorian Ranged Weapons
- [x] Old Republic / Sith Empire Armour
- [x] Old Republic / Sith Empire Weapons
- [x] Rebel Alliance Armour
- [x] Rebel Alliance Weapons
- [x] Separatist Weapons
- [x] Pawnkinds

## Testing
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony for an extended period

### CODE REVIEW

**Comment by Arcalane** [comment]
'scuse the mess, I branched off the old master originally (which is now very, *very* out of date) and in order to streamline my testing & such I rebased my local branch to the 5.6 hotfix branch which has some files that aren't in the main dev branch right now.

**Comment by Arcalane** [comment]
Finally solved a problem I was having with disappearing ammo, basically ended up rewriting all the projectiles from scratch. Galactic Empire weapons (except the flamer) now have a WIP set of values for testing.

Going to need to gather more appropriate values to make the weapons more distinct and flavourful, but I am now making something approaching serious progress.

**Comment by Arcalane** [comment]
After a lot of wrangling XML (mostly to wrap up grenades) I now have most of this in a functional state and ready for review. Things that are explicitly NOT covered:
- Turrets (Core)
- Shields (Core)
- Droids (Droid Depot)
- Droid Components (Droid Depot)

**Comment by Arcalane** [comment]
Tweaked material stats for durasteel (a bit more sharp armour, much more blunt armour) for consistency, and adjusted mandalorian armours- material multiplier was reduced on non-heavy armours to make quality more important (particularly for steel). Also reorganized the patch operations to put the heavy armours together for convenience.

**Comment by Arcalane** [comment]
Dug into the jetpacks thing. Turns out they had custom ability comps for their jump power, presumably to allow infinite jumps and no fuel cap, which might be why it was setting off the sharp pen notice when AI pawns tried to use them. I've replaced this with the standard royalty-style jump pack functionality with the same range, but with 3 extra charges and 10 less chemfuel per charge as compensation. I've also removed the speed penalty for just having a jetpack equipped.

**Review by N7Huntsman — APPROVED** [review]
I patched bulk into a few clothing items to ensure the autopatcher wouldn't try to patch them, but everything else looks good.

**Comment by Arcalane** [comment]
Nice! I'll be doing some tweaking of the patches as I do some proper playtests -- I'll probably need to buff the armours a bit to bring them in line with the Recon and Marine armours in terms of overall + limb protection, and I think I also need to adjust the performance of the blaster rounds somewhat.

Some weapons will also need tweaking on an individual basis, and I have a few ideas I want to experiment with to offset the relative ease of logistics for blaster ammo. I may also try adding an altfire to the TL-50, but that's for future tests.

**Pull request merged**
