### PR TITLE
Rimsenal Revision 

### PR DESCRIPTION
**Pull request by Tostov**
## Additions

GD armor stuff. Korp armor stuff.

## Changes

Revised the mechanics of the GD weapons to match their new appearance/specs. In general, mag capacity increase, switchced to 4.77x33 caseless since description does state rifle runs on caseless uses and all the weapons are based off of the same core platform. Sniper version now a weird burst rifle like the actual G11 to make up for the lack of per hit power, the other ones function 'normally', pistols now all share the same ammo but it has a lower power statline for everything but the hybrid pistol, which shares with the hybrid rifle.

In general the caseless rounds make the GD weapons generally better against industrial tech level targets but worse against spacer ones, now practically requiring the hybrid rifle/pistol to deal effective damage against stuch targets.

Swapped the basic TE weapons from highish blunt with lowish damage to the opposite, i.e. high blunt damage with comparatavely lower blunt penetration. Blast weapons now have lower damage but higher penetration. Tweaked the lance's stats/effect a bit and turned it into a laser since we have the stuff for it now and that is functionally probably the intent, and gives us the option to give it falloff for the damage.

Removed the thermal damage aspect from JI weapons, as descriptions no longer really imply heating. Switched siege cannon to now use the same alloy ammo as the description has changed, and added a variant of the round for the Korp Armor weapon. JI weapons now have middling sharp penetration, but very high blunt penetration meaning that even deflects do the majority of the damage anyway, reflecting the very high armor penetration the weapons have in vanilla.

Siege cannon now launches a ball that explodes into a lot of heavy fragmentation. AMR now acts more like a AT launcher in its stead.

Reduced the damage/recoil on YP pistol, rifle, heavy rifle and vector shot. Increased the penetration greatly (24/30/36/30). Spike rifle is now capable of (low RoF) automatic fire. In general YP weapons automatic functions should now be better, but they'll generally lag behind conc. against very heavily armored targets due to poor individual shot damage. Swarmer now has automatic fire function.

Reduced the blunt armor of federation non-humans other than the federator, slighlty improved their accuracy stats. Reduced the spread on the plasma cavalier/caster, reduced the projectile velocity. Improved the RoF on the rifle, reduced the RoF on the carbine and made it 1/3/5 burst.

WIP - tweak some of the feral armor values for the feral mail/plate to be more consistent with other gear.

Enhanced vanilla - Fixed the charged frontier rifle, boosted the melee stab penetration a bit to match the description of it being a monobayonet, and to make it a little more appealing than just stepping a tile back and shooting with it.

## Reasoning

GD stuff has gotten a visual overhaul and the current stats now don't really pair well with what they are visually.
For the GD armor, stats are actually a little better than expected for the given tech/resource input, probably by about 10-20% or so. This is to account for the fact that the GD armor doesn't have quality any more, and realistically the player is always going to be making good or better quality armor in the first place.

The security armor in particular is a semi-powered type that provides some offset without completely negating its own weight like the upgraded versions. Tech wise it still requries microelectronics + another research since the armor is only manufacturable at the greydale bench, which needs to be researched after microelectronics.

In general, the rationale behind the RImsenal weapon changes for the non-GD manufacturers is to make them a viable alternative, especially at their desired niche, compared to charge weapons.  

JI weapons work fairly equally well against most mechanoid targets, since they can put out heavy hits good at destroying internals, and all of the weapons are capable of striking through heavy mechanoid armor thanks to exceptionally high blunt penetration. The downside is of course that both the weapons and ammunition are heavy, and the resulting recoil is high, limiting full auto use to very close quarters in general

TE weapon's high lethality against targets with low blunt armor helps improve their performance against federation gear in particualr which tend to tend towards high sharp armor and low blunt armor which is well rated against charge weapons, and they also happen to work particuarly well against other targets with fairly low blunt penetration, such as tribals or early industrial tech levels, where the high raw damage makes it effective without making them too effective against power armor or other heavy targets.

YP weapons are probably the most simmilar to conventional charge weapons, but trade the versatility of different ammo types for better handling and the mid to close range where their low recoil full auto gives them an edge in securing hits, even if the overall damage output is simmilar. The high AP + volume of fire should also help the weapons more effectively suppress hostiles.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by Tostov** [comment]
Use PR #994 to revert the RS_Apparel_CE changes which should resolve the conflicts.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
The GD artillery armor doesn't appear to be firing at the moment.

**Comment by Tostov** [comment]
Getting other errors from the latest build version here probably because of the merging conflict, I'll try refreshing it and also just tweak the smartguns as well anyway.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
Everything appears to be functioning as intended, but I am getting one minor start up error for 

`XML error: Duplicate XML node name AimingAccuracy in this XML block: <statBases><ShootingAccuracyTurret>0.96</ShootingAccuracyTurret><AimingAccuracy>1.0</AimingAccuracy><AimingAccuracy>1.0</AimingAccuracy></statBases>` inside of `Turret_ShardSentry`

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
