### PR TITLE
Pawnkind autopatcher bugfix

### LINKED ISSUE #1210: [Bug]: Autopatcher Logic Bug
**Combat Extended version:** Latest Dev

**Description**
It was pointed out that the current logic of the autopatcher for pawnkinds may be targeting pawnkinds that have already been patched, potentially overwriting and causing issues.

### PR DESCRIPTION
**Pull request by Caulaflower**
Fixed a bug where patched defs would get patched again
Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

Closes #1210

### CODE REVIEW

**Review by N7Huntsman — APPROVED** [review]
This does appear to fix the problem.

**Review by perkinslr — CHANGES_REQUESTED** [review]
Spaces in file names play hell with the tooling of those of us that live on the command line.  They also randomly break other things.  

Please use a hyphen, or underscore, or a directory seperator, or just omit the space and use TitleCase, depending on what you are trying to convey.

**Comment by perkinslr** [comment]
Also, source leaking outside the Source directory is probably a mistake.  I would think these should go in `Source/CombatExtended/Compatibility/AutoPatchers` or similar.

**Comment by Caulaflower** [comment]
It seems that I accidentally added files which weren't supposed to be in this branch, I think everything is good now

**Review by perkinslr — APPROVED** [review]

**Pull request merged**
