### PR TITLE
Vanilla Factions Expanded - Insectoids [WIP]

### PR DESCRIPTION
**Pull request by onigamii**
# Vanilla Factions Expanded - Insectoids

Making this PR to keep track as i work on it and let other people play with it if they want.

## Progress
- [x] **Bodies**
  - [x] Boomtick
  - [x] Scorpion
  - [x] Wargling
- [ ] **Hediffs**
- [x] **PawnKindDefs**
- [x] **Scenario**
- [x] **ThingDefs_Items**
  - [x] Leathers
- [x] **ThingDefs_Misc**
  - [x] Apparel
  - [x] Weapons / Ammo
- [x] **ThingDefs_Races**
  - [x] Insects
- [x] **ThingDefs_Races_VatGrown**
  - [x] Boomtick
  - [x] Cuterpillar
  - [x] Gigascorpion
  - [x] Gigawig
  - [x] Megacricket
  - [x] Milkbeetle
  - [x] Monstosity
  - [x] Princess
  - [x] Royal Larva
  - [x] Royal Maggot
  - [x] Spiderweaver
  - [x] Titanbeetle
  - [x] VAT Gigalocust
  - [x] VAT Megapede
  - [x] VAT Megascarab
  - [x] VAT Megaspider
  - [x] VAT Spelopede
  - [x] Wargling
  - [x] Worker Ant

## Notes
- Haven't decided the magazine size for the plasma weapons yet, currently the cutter / scattergun / beam rifle share a mag size of 50 each with the piercer having a 20 "round" magazine.
- I'm still tweaking the armor / damage pen numbers are they're most likely to change as i work on the patch.

### CODE REVIEW

**Comment by onigamii** [comment]
Alright another update, massive thanks to Tostov for providing the patches he'd already done. This one patches all the insects wild / vatgrown, riot gear, adds ammo recipes, scenario, pawnkinds, animal resources, etc.!

**Note:** I'm still unsure of how i want to make the ammo work, maybe add ` Stun ` secondary damage to the Piercer, ` Cut ` to the Cutter and maybe ` EMP ` to the other two.

**Comment by Tostov** [comment]
The charge lance should be removed/swapped for something else in the mercenary start scenario, as the weapon itself will disappear after picked up and dropped.

**Comment by Breadbox2k19** [comment]
Balance wise I would like to raise some issues, most of the insectoids excluding the queens and megapedes are too way tanky, they have too much armour compared to regular insectoids, megaspider has 6 sharp(Royal and gigalocusts have 13+ Sharp and ridiculous blunt armour), their health scales are also too high, insectoids in CE gain armour loses health, for example Megaspider only have 1.8 health in CE.

Please consider balancing their armour and health accordingly based on their combat power values. I would be happy to make those edits if you don’t mind.

**Comment by Tostov** [comment]
Given that the majority of the insect values themselves were done by me and are yet to be adjusted by andross, I can explain some reasoning behind them.

A) In vanilla, gigalocusts have0 .7 sharp armor, as opposed to the 0.27 that vanilla megaspiders have.
B) Insectoid armor doesn't actually cover a very significant amount of the pawn, for example it covers none of the head or legs, only the neck/torso equivalents, meaning that for _every_ insectiod, you can go to town on them with a steel sword and lop off all their legs.
C) The insane blunt is from the fact that vanilla insectiods have a 3MPa per 1mmRHA defensive  profile.
D) In regards to armor/durability, the vat grown variants should be reasonable durable as to actually make them useable, as you're already sinking in an exotic resource into a creature that you don't really have full control over.

I did forget about the HP adjustment values, however tbh, I don't think there's a significant need to reduce the armor/HP drastically of many/any of the species. Pretty much any raid of them of equal points gets absolutely shredded by an equivalent raid of pirates.

**Comment by N7Huntsman** [comment]
I'd like to see a general increase in Sharp Armor Penetration, especially for the larger insects. In the lore, insects are genetically-engineered and the larger ones were originally intended for combat against, among other things, mechanoids.

With that in mind, larger insects, in quantity, should have enough Sharp AP to be a serious threat to colonies with late game equipment. Megapede's have a pair of mandibles attached to its face that are like a pair of hydraulic shears, and should be able to cut clean through power armor. The Gigascorpion and Gigalocust should be similarly dangerous. The Royal Megaspider should be a general improvement over the vanilla Megaspider, with incrementally stronger attacks and AP, and a boost to their armor.

**Comment by Tostov** [comment]
It's worth nothing that the larger combat insects in general _do_ have assault methods that should allow them to punch through power armor. The exception is the megapede because it really is more of a tanky/sapper rather than a striker unit.

The queen/royal megaspider/gigalocust/wargling/monstrosity all have the same penetrator type stab that the vanilla megaspider has (at various strengths, the monstrosity is the strongest, with the wargling at the weakest), giving them sufficent penetration to punch through. The gigascorpion has its stinger which can punch through power armor, and the claws which can cause a small amount of blunt damage through it. The issue is that bugs will do their regular cut attacks a lot of the time against targets where it wouldn't do anything, which is probably fine because otherwise they absolutely would shred everything (in the same way having only the stab on a plasma sword or hammer hit on the zeus would).

With the monstrosity, the stats were higher previously, but apparently they can randomly occur from the incubator as an accident (and might be the most frequent one maybe?) so I did tone the stats down because losing 3-4 pawns at random because the incubator derped isn't something that is probably worth the trouble.

**Comment by N7Huntsman** [comment]
> I did tone the stats down because losing 3-4 pawns at random because the incubator derped isn't something that is probably worth the trouble.

I'm alright having them be fairly strong, since they automatically die after a few hours. With that in mind, I'm okay with the idea of having a situation where it's more practical to seal the doors than to try to dogpile it to kill it. If you're taking it head on Space Marine style and don't want to suffer heavy loses, you attack it with a 3-5 person kill-team in heavy armor with a balanced array of hard-hitting weapons. The Monstrosity is a dangerous combination of speed, armor, and health, without having an overly large amount of their. It doesn't have so much armor that you can't hurt it with charge ammo or powerful anti-armor rounds, but it's got enough health that it can soak up a lot of small hits and keep going for a while. You could probably kill it with a solid hit or two from an AT-rocket, but the thing is fast and tends to close the distance too quickly.

**Comment by N7Huntsman** [comment]
> The queen/royal megaspider/gigalocust/wargling/monstrosity all have the same penetrator type stab that the vanilla megaspider has (at various strengths, the monstrosity is the strongest, with the wargling at the weakest)

That sounds alright. Just bear in mind that whereas mechs tank with very heavy armor, bugs mostly tank with medium armor + good health.

**Comment by N7Huntsman** [comment]
> For the titanbeetle I just wasn't sure whether to go strong enough to pulverize torso in power armor or not. Its horn swing should be strong enough to snap the neck of someone wearing a steel vest or nearly crush to death someone in power armor, but it's not actually a dedicated combat bug and doesn't show up in the insectoid raids.

A fair point. I'd say make it similar to the elephant's blunt attacks with their tusks with more armor, but not enough that it can tank in the same capacity as a dedicated combat-type like the Megapede.

**Comment by Tostov** [comment]
> > I did tone the stats down because losing 3-4 pawns at random because the incubator derped isn't something that is probably worth the trouble.
> 
> I'm alright having them be strong (the base mod says "nigh unkillable"), since they automatically die after a few hours. With that in mind, I'm okay with the idea of having a situation where it's more practical to seal the doors than to try to dogpile it to kill it.
> 
> If you're taking it head on Space Marine style and don't want to suffer heavy loses, I think you attack it with a 3-5 person kill-team in heavy armor with a balanced array of hard-hitting weapons. The Monstrosity is a dangerous combination of speed, armor, and health, without having an overly large amount of either. It doesn't have so much armor that you can't hurt it with charge ammo or powerful anti-armor rifle rounds, but it's got enough health that it can soak up a lot of small hits and keep going for a while. You could probably kill it with a solid hit or two from an AT-rocket, but the thing is fast and tends to close the distance too quickly.

Yeah I wasn't sure at the time I did these number if the incubator required you to actually babysit it and it popped out immediately, or whether you could seal the room. Knowing that you can turn it on and then leave it until the bug comes out makes it a lot more reasonable to have the monstrosity be insane levels of strength.

> > The queen/royal megaspider/gigalocust/wargling/monstrosity all have the same penetrator type stab that the vanilla megaspider has (at various strengths, the monstrosity is the strongest, with the wargling at the weakest)
> 
> That sounds alright. Just bear in mind that whereas mechs tank with very heavy armor, bugs mostly tank with medium armor + good health.

Yeah for the bug armor after some testing it can probably be toned down a little bit, since the values as of current were based off of the megaspider having 6mm sharp rather than the 4mm it actually has. The main thing in relation to this would be bringing the royal gigalocust into the sub 14mm armor rating area, so regular AP rounds work against it.  That being said, insects don't have particuarly great coverage for their armor, and the abillity to resist gunfire in their current state still has them losing against regular raids, so it might be worth increasing their speed or decreasing their threat point cost to compensate, but I'm not really 100% sure. Both megapede variants are lower sharp but higher blunt than the centipede, which gives them an interesting abillity to resist 7.62x51/54r non-sabots particuarly well. The vat grown variants probably don't need an armor decrease just because they don't show up in enemy hands and the current values are pretty decent anyway.

> > For the titanbeetle I just wasn't sure whether to go strong enough to pulverize torso in power armor or not. Its horn swing should be strong enough to snap the neck of someone wearing a steel vest or nearly crush to death someone in power armor, but it's not actually a dedicated combat bug and doesn't show up in the insectoid raids.
> 
> A fair point. I'd say make it similar to the elephant's blunt attacks with their tusks with more armor, but not enough that it can tank in the same capacity as a dedicated combat-type like the Megapede.

Ahh, yeah I probably should've used the elephant as a baseline for the horn attack.

**Comment by onigamii** [comment]
Added the new numbers by @Tostov  and fixed the psychic warhead ` graphicClass ` class now it works fine, everything should be ready for merging.

**Comment by N7Huntsman** [comment]
A few items that I need to check the status of before merging:
- Charge lance in the starting scenario
- Megepede leg armor
- Hediffs (are they still to be done, or just not in need of patching?)

**Comment by onigamii** [comment]
> 
> 
> A few items that I need to know the status of before merging:
> 
>     * Charge lance in the starting scenario
> 
>     * Megepede leg armor
> 
>     * Hediffs (are they still to be done, or just not in need of patching?)

I thought i had pushed the charge lance changes my bad, the hediffs don't need to be patched afaik and i was waiting on tostov since he has more experience doing animals.

**Pull request merged**
