### PR TITLE
Add the new 66mm Thermal Bolts

### PR DESCRIPTION
**Pull request by SamaelGray**
## Additions and changes

- Add the new mechanoid-built 66mm thermal bolts.
- Changed the ammo type used by explosive bolt projectors to 66mm thermal bolts along with other mech stuff that use 60mm mortar shells.
- Reshuffled the mech ammo production recipes to the Versatile Assembler building instead of the Artillery Foundry to reduce clutter. The Artillery Foundry is specifically used for artillery shells and not random ammo types which the Versatile Assemble is a better place for those recipes.
- Tweaked the 80mm Fuel Cells' mass to a more sane value of 0.86 based on the projectile mass increase in the spreadsheet, the older 6 grams for the projectile mass was unreasonably low.
- Adjusted some left-out recoil values.
- Changed the weapon tag of the Thermal Bolt Projector to `MechanoidGunIndirect` so that it's not the same as the vanilla needle gun.
- Relocated mech pawnKind patches to their race patch folder.

## References

- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit#gid=1393347070

## Reasoning

- Mechanoid weapons use ammo specific to them, not human-built ammo.
- The new shells are Incendiary-Thermobaric similar to 105mm incendiary shells.
- Duplicate sound nodes don't have an effect, so I removed the `MortarIncendiary_Explode` node from the secondary thermobaric explosion of 80mm fuel cells, 105 and 155mm shells
- The charge mortar shells (`Bullet_ChargeMortarShell`) which were 81mm shells without the fragmentations bit are replaced with the more unique and effective 66mm shells.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (no errors)

### CODE REVIEW

**Comment by N7Huntsman** [comment]
Use a scaled down version of `Things/Projectile/Mortar/Charged`, which is what we use for the Royalty mech cluster auto mortar.

Additionally, I find the combination of HE + Incendiary peculiar. I'd either go with a pure HE shell or an Incendiary shell with a small thermobaric element, similar to existing mortar shells, since purely incendiary shell would have a larger radius but would lack the direct stopping power.

**Review by albertbokor — APPROVED** [review]
Let's see how this motherfucker handles!

**Comment by albertbokor** [comment]
why no incendiary explosion sound?

**Comment by ItsSamGray** [comment]
> why no incendiary explosion sound?

Only the first explosion sound gets registered and the two don't get mixed.

**Review by albertbokor — DISMISSED** [review]

**Review by albertbokor — APPROVED** [review]

**Review by albertbokor — DISMISSED** [review]

**Review by albertbokor — DISMISSED** [review]

**Review by albertbokor — APPROVED** [review]

**Pull request merged**
