### PR TITLE
Rocket thruster smoke and flame

### PR DESCRIPTION
**Pull request by CMDR-Bill-Doors**
## Additions

A comp for projectile trails.
variables:
FleckDef: fleckdef.
flecksPerTick: how many flecks will be generated per tick. These flecks will be evenly distributed between the where the projectile was and where it is now.
scale: a floatrange for, well, fleck scale
thickness: amount of flecks generated every time, 1 is usually enough, though you'll need more for thruster flame.
cutoffTickRange: a floatrange. the fleck generation will gradually fade out from min tick to max tick.

## Changes

Added example comp for 50mm and LAW, it'll be great if anyone is willing to do the rest.

## Reasoning

For the looks.

## Alternatives

Bruh

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by SamaelGray** [comment]
Please set the indentation standard in your software of use to tabs instead of spaces, the whole CE and its submods are using tabs for indenting. Thanks.

**Review by N7Huntsman — DISMISSED** [review]
No issues in testing. I'll add some new rocket parent bases in varying sizes so the smoke and flame can be easily assigned to projectiles.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
I'm getting this error when testing the 50mm rocket. https://pastebin.com/kUmppbnL

**Review by N7Huntsman — APPROVED** [review]
Works in testing now. As stated, could probably implement some rocket projectile parents in a few different sizes, but that's just xml and can be done later.

**Pull request merged**
