### PR TITLE
Stat tweaks

### PR DESCRIPTION
**Pull request by LockdownX7**
## Changes
- Display chance factor for each tool in melee DPS stat
- Calculate correct melee armor penetration values for recipe bill info windows
- Final values for melee damage and AP stats now have the correct value in the explanation panel

### CODE REVIEW

**Review by N7Huntsman — COMMENTED** [review]
Regarding the chance factor in the DPS section, it only seems to appear for attack tools whose chance factor is not equal to `1`. I'm not sure if this is intentional or not.

**Comment by LockdownX7** [comment]
It was intentional, but on second thought it's clearer for players if shown always. I updated the PR accordingly.

**Review by Breadbox2k19 — APPROVED** [review]
Helpful update, but the chance of melee attack is bit of a mystery to me, what is the current determination and how does chance factor.......factor into this?

**Comment by LockdownX7** [comment]
Chance factor is just a selection weight, and defaults to 100%. A tool's selection chance is its own chance factor divided by the sum of all the tools' chance factors. For example, if you have a weapon with two tools at 100% factor, and a third tool with 200% factor, then the first two tools each have a 25% chance of being selected, and the third one has 50% chance.

**Pull request merged**
