### PR TITLE
Simplified ammo setting

### PR DESCRIPTION
**Pull request by Dr-Slump**
## Additions

Adds a setting to reduce the number of ammo variants available in game (off by default).

## Changes

When turned on, the list of available ammo variants is reduced:
* Pistols and rifles only have FMJ (no HP, no APs, no sabot).
* Advanced guns lose charged AP ammo.
* Shotguns lose slugs and beanbag ammo.

No change to grenades or shells.

## References

N/A

## Reasoning

I implemented this for myself because late-games were getting really messy. It's easy to end up with 50 types of ammo, taking storage space and requiring additional pawn management.

At the same time, turning off the ammo system isn't as fun.

The change is only in code. I don't think it breaks any gun, unless they only use a single type of ammo (e.g. HP-only pistols? I haven't seen any, but I haven't tried all the mods).

I figured I might as well share my work, so I cleaned it up.

No hard feelings if you reject it :)

## Alternatives

Removing all these ammo types from definition files isn't an acceptable solution, obviously.

Another option would be to configure the list of ammo types in settings, but this would add a lot of settings (there's 22+ ammo classes), and you could easily end up with a broken game if you disable too many...

## Testing

- [X] Compiles without warnings
- [X] Game runs without errors
- [X] Play-tested a colony (I tested most of the guns from CombatExtendedGuns)

### CODE REVIEW

**Comment by N7Huntsman** [comment]
I can't actually seem to find the button to toggle this in the settings menu.

**Comment by Dr-Slump** [comment]
Hi,
I did not include an updated DLL in the pull request, maybe that's the reason?
I assumed the reviewers would re-compile the DLL, but maybe that was the wrong assumption.
I pushed a compiled DLL, sorry about that.

**Comment by N7Huntsman** [comment]
Ah, my mistake, then. As a note, it's general practice for the CE repo to include a recompiled DLL, as a number of the testers (myself included) work mainly with .xml and don't have stuff set up on our ends to wrangle with the other aspects.

Two notes regarding what I found in testing:
- It seems to require reloading the game for enabling/disabling it to take effect, which makes sense. You might add a warning in settings, though.
- While I can no longer spawn the different ammo types in dev mode and they disappear when dropped, raiders will still spawn with them.

**Comment by Dr-Slump** [comment]
Got it, thanks for the tip!
And thanks for the bug report, indeed I missed the raiders/merchant loadout generator. I guess I didn't notice because the ammo would disappear on drop. I'll figure it out!

**Pull request merged**
