### PR TITLE
VWE Makeshift patch fix

### PR DESCRIPTION
**Pull request by SamaelGray**
## Changes

- What it says on the tin, no more special gimmicks, no more extra gizmos, no more headaches... (Makeshift ammo does not exist, scavenge or trade for it.)

## Alternatives

- The alternatives are dead.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by T-rexsuper1** [comment]
The fact that makeshift ammo does not exist makes the entire mod utterly pointless and useless, the point of CE patching is to make mod not only playable but also usable, adding a couple new ammo calibers and recipes for them wouldn't hurt but the mod is worthless without them.

**Comment by albertbokor** [comment]
Always was.

**Comment by T-rexsuper1** [comment]
> Always was. Teching up in RW is just way too easy for these to be a legit useful niche.


I beg to differ. These guns are way less expensive and easier to craft, don't need electricity for crafting, and way faster to research than normal guns. They do fill a niche as early game defense weapons and they need ammo for that to work.

**Comment by albertbokor** [comment]
make a blunderbuss, lol

**Comment by albertbokor** [comment]
or just do as everyone else and accept the charitable donations given by the (hostile) visitors

**Review by albertbokor — APPROVED** [review]

**Pull request merged**
