### PR TITLE
HALO: Rimworld Auxiliary Combat Armory

### PR DESCRIPTION
**Pull request by onigamii**
## Additions
Patches [HALO: Rimworld Auxiliary Combat Armory](https://steamcommunity.com/sharedfiles/filedetails/?id=1961456342)

The plasma version of the charge guns are essentially the same, they just fire plasma. Give this they have the same stats just a bit less recoil and use the new **Plasma Cells** ammo introduced from FT.

**PS:** Should probably look to remove ` <explosionRadius> ` from the Plasma Cells, don't like that my screen shakes every time the guns fire.

## Testing
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested

### CODE REVIEW

**Comment by nomoretime0723** [comment]
I have tested the patch and didn't encounter any errors. Well had one error log but not this HALO mod but the other HALO mod which adds mechs.
have played for half an year (in game time) with about 124 mods
tested all of the weapons. balanced seemed ok it was just like a charged rifle.

**Comment by JermandJer** [comment]
The tactical magnum is not fully automatic despite its description saying so
And I think the normal charge magnum needs to be buffed to a 8x35mm charged, it's firing the same round as the smg, despite being a literal hand cannon. It's range and fire rate is shit so it's basically useless without a damage buff
It is outplayed by every other weapon using 6x18 charged

**Comment by onigamii** [comment]
### Changes
- Buffed the 105mm Shaped Charge
- Added missing tags
- Charge Pistol now has a 3 round burst

**Comment by N7Huntsman** [comment]
The Charge Magnum melee patch apparently didn't work, getting the error related to missing CE-melee stats. There may well be others.

**Comment by onigamii** [comment]
## Changes
- Fixed broken tools patch for the Charge Pistol / Magnum
- Gave the EMP Launcher a custom ammoSet with 40x46mm grenades

**Comment by N7Huntsman** [comment]
The plasma shotgun is still not working like a shotgun.

**Comment by onigamii** [comment]
Hi, just getting some free time before i have to go back to the grind. Uuh added the respective ammo for the plasma shotgun with what i think is proper "plasma" ammo anything hit me back.

**Comment by onigamii** [comment]
> * The Charge Battle Rifle doesn't have melee stats.
> * Should the Rocket Launcher be automatic? It strikes me as a bit overkill for any target, really.
> * The grenade/EMP launcher should be able to fire at locations.
> 
> Other than those items, everything else seems good to go.

Done. Minor typo in the tools patch, the emp launcher can target locations and the rocket launcher now fires 1 rocket and has a slightly higher warm up time.

**Pull request merged**
