### PR TITLE
Patch for [K4G] Rimworld War 2

### PR DESCRIPTION
**Pull request by Airomeda**
## Additions

Describe new functionality added by your code, e.g.
- New Anti-Tank Rockets ammo (Panzerfaust 50 and 60, Type 74mm Rockets)

## Changes

Describe adjustments to existing features made in this merge, e.g.
- None, except my sanity

## References

Links to the associated issues or other related pull requests, e.g.
- None, probably world war 2 reference

## Reasoning

Why did you choose to implement things this way, e.g.
- because yes

## Alternatives

Describe alternative implementations you have considered, e.g.
- nope, this is painful already

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

## Current Issues
- ~~Backpack rendering went borked, I've tried various approaches and to no avail.~~ this has been fixed, thanks albertbokor!
- ~~Anti-tank grenade projectiles still not working~~
**- Note: this is the 2nd pull request as the previous one is closed because it's quite messy**

### CODE REVIEW

**Comment by Airomeda** [comment]
My previous comment for @N7Huntsman from last closed pull request : 
The original mod decided to create weapon Defs using the same parent within their class, ParentDefs I'm speaking of mostly being an American weapon. So trying to patch every weapon from each nation isn't possible using the CombatExtended.PatchOperationMakeGunCECompatible operation because it seems most weapons stats are based on the ParentDefs (so they had no individual combat stats, to begin with), if I were to patch the ParentDefs alone other weapons basing off of it will follow the same stats as the parent (it would be weird to see German K98 Karabiner using the same caliber as American M1903 Springfield which is .30-06 Springfield as the caliber. To be honest this patch would've been easy without replacing every weapon Defs to be using their own combat value

**Comment by albertbokor** [comment]
Still have no idea what's with the backpacks, do we just switch back the still broken ones to ce backpack?

**Review by albertbokor — DISMISSED** [review]
It's working, LGTM!

**Comment by N7Huntsman** [comment]
Hmm, no errors on start-up this time, but I di think I'll take a poke at this and see if there's a more elegant and tidy solution to be found...

**Review by albertbokor — APPROVED** [review]
LGTM!

**Review by N7Huntsman — APPROVED** [review]
I'm still not super pleased with the formatting of this patch and will probably revisit fixing it at a later date, but everything looks functional right now.

**Pull request merged**
