### PR TITLE
Escp-Spriggan Compatibility Patch

### PR DESCRIPTION
**Pull request by ViralReaction**
## Additions

Describe new functionality added by your code, e.g.
- Compatibility patch for creatures in mod
- Patch creature body

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (few minutes)

### CODE REVIEW

**Comment by N7Huntsman** [comment]
Any specific reason the Burnt variant had its ranged attack removed?

**Comment by ViralReaction** [comment]
Forgot to patch that. The removal was during testing mobs.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
What's here looks good. However, something I overlooked the first time, the scenario needs ammo added. Looks like it matches the vanilla tribal weaponry, so you should be able to just mostly copy-paste the vanilla tribal scenario stuff over.

**Comment by ViralReaction** [comment]
Patched missing scenario. Equal arrows to tribal.

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
