### PR TITLE
Underbarrel improvments

### PR DESCRIPTION
**Pull request by MaxDorob**
## Changes

Describe adjustments to existing features made in this merge, e.g.
- oneAmmoHolder works correctly now
- fixed underbarrel uses burst count from parent weapon
- custom labels for underbarrel and switch back gizmos

## Reasoning

- I don't know, check #3024 

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony (changed and tested AK-74 + GP-25 )

### CODE REVIEW

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
Currently, for underbarrel weapons that use `oneAmmoHolder`, we don't need to have `propsUnderBarrel`, since we just take that info from the base weapon. However, if we delete `propsUnderBarrel` entirely, the AmmoInjector throws an exception.

Log: https://pastebin.com/mndn3jnS

To avoid this becoming a problem, we should either add an appropriate null check or just put `oneAmmoHolder` inside of `propsUnderBarrel`.

**Comment by N7Huntsman** [comment]
Also, the labels work correctly, but `oneAmmoHolder` does not.

We want it to fire the using the underbarrel weapon's stats and projectile, but at the moment it fires the base weapon's one.

**Comment by Jan-Blasiak** [comment]
Instead of adding anything meaningful to the conversation I'll instead say that I really appreciate all the stuff you guys are doing and can't wait for the 1.5 update.

**Comment by MaxDorob** [comment]
Now null propsUnderBarrel interpreted as oneAmmoHolder is true

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
The new labels, gizmo textures, and `oneAmmoHolder` system are all working correctly.

However, I encountered some buggy behavior that occurs when loading saves with an equipped weapon switched to the underbarrel.

Details here: https://discord.com/channels/278818534069501953/322827713335394304/1248800432818487297

**Review by N7Huntsman — APPROVED** [review]

**Review by Thorbane — APPROVED** [review]

**Pull request merged**
