### PR TITLE
Rimsenal Collection Patch

### PR DESCRIPTION
**Pull request by N7Huntsman**
Integrates my patches for the Rimsenal collection, previously maintained as an external patch.
- Rimsenal - Core
- Rimsenal - Enhanced Vanilla Pack
- Rimsenal - Feral Faction Pack
- Rimsenal - Federation Faction Pack
- Rimsenal - Security Pack

Quite large, and somewhat dated, so in addition to a functionality check, a good balance pass will probably be necessary. Make sure to test with varying pieces and parts loaded, to ensure the conditional patching is working as intended.

### CODE REVIEW

**Comment by N7Huntsman** [comment]
I still need to revise some ammo/projectiles, as they're inheriting from a patched-in base, which we know doesn't work.

**Comment by Tostov** [comment]
YP Weapons: Overall, for the regular weapons I’m largely satisfied with their performance but I’d like to see the more unique weapons in the line made a bit more consistent with their vanilla variants
Shard Rifle - Personally, I’d like to see the full auto capacity scaled up from 5 to 6-8sih, as well as the range toned down to probably around 40-44ish to be closer to the other sub-carbines, which it kind of behaves like.
Dual Wield pistols - With new ammoconsumedpershot part of the ammouser comp, there’s no reason not to make this just fire a 2 pellet shot and restore it’s full auto capability.
Spike Rifle - Ignoring the current ammo stat at the moment, it should really have an extreme amount of penetration for the shot, somewhere in the range of 30-40mmRHA imo. I wouldn’t set the damage too high but the vanilla version is actually only outmatched penetration wise by the JI series of weapons and the anti-material rifle of the vanilla options.
Microwave/Nanoswamer/Vector Shot in general - I think these three would benefit from having some sort of universal power cell type ammo that all three share, since they all have very strange weapon setups.
Microwave Emitter - I think it would be reasonable to make the damage def for this (and consequently the grenades) apply CE’s muscle spasms hediff for downing targets, as this serves much the same role. The amount applied could be limited, since targeting heat armor makes it effective against a wider range of targets but it should be considered.
Swarmer - Not much to say, I think restoring it to its conventional setup and giving it a fair amount of low damage pellets with lowish spread would be the way to go.
Vector Shot - Rather than a half assed SMG, now that we have a precedent to work off of, it should be converted to a short range mortar type weapon with invisible projectile as the original in vanilla functionally is. This can be achieved by giving the projectile a very high gravity factor which allows us to use a fairly high speed projectile to give it minimal travel time.

JI Weapons - Personally, I am not a very big fan of how some of the weapons are currently implemented in this patch. In general, I’d like to see them adjusted more towards being high power single shot weapons, especially with the implementation of AP-I rounds in conventional rifles pretty much pushing them out of any niche that the burn + bullet damage that they previously had.
JI Molten Rifle/Pistol in general - As noted before, I’d like to see the ammodef for the conventional molten slugs changed to be more akin to a slug specifically rather than a chonky battle rifle bullet. I think maintaining the incendiary effect is quite interesting and isn’t worth removing, but the overall round specifics should be based on a beefier 12 gauge slug.
JI Molten Rifle - Matching with the change in interpretation to shotgun, it should have it’s burst/automatic modes changed to match the shot counts for automatic shotguns rather than assault rifle (i.e. 3 on auto, 2 on burst rather than 5/3), assuming it would retain it at all.
JI AMR - Ideally could use an increase in damage and blunt penetration buff, giving it something akin to the properties of the 23x75mmR but in AP-I form, but with its current sharp penetration retained.
JI Siege Shotgun/Suppressor Cannon - My suggestion would be to merge the ammo type for these two weapons, and use the ammoConsumedPerShotCount to have the siege shotgun fire 4 shots as a spread and the suppressor fire what is functionally the same shot but individually as part of a burst. Part of the idea for this is due to the vanilla suppressor cannon being a lower power/penetration weapon that fires a significant number of rounds, closer in performance to a low RoF Minigun than the single high damage shot profile that all other JI weapons use.
JI Siege Cannon - I’m mostly fine with the performance characteristics of the weapon, though I don’t think there’s any need for the weapon to have such a long cooldown/warm-up (4 seconds is absurdly long) or sub 100% sight accuracy.

TE Weapons - As a whole I think these could use a bump in their blunt penetration power or in their damage, either cementing their role as a anti-blunt armor specialty weapon with consistent damage, or as a weapon designed to specifically punish low blunt armor levels. I think that as per their descriptions/implementation in vanilla, the kinetic pistol/rifle/long rifle should all be given fairly fast warm-up times for their respective weapon classes akin to the VWE:Quickdraw guns. The semi-energy based nature of the weapons also makes them an ideal candidate for merging all of the ammo into one power cell type munition and using the ammoConsumerPerShotCount part of the verb to differentiate the weapons’ ammo consumption.
TE Kinetic Pistol - Given that the functionality of the pistol’s ammo is shared with the rifle’s, and that the rifle ammo should be reasonably strong, I’d suggest giving it a smaller ammo pool, closer to 7-9ish rounds rather than the 12 it has now.
TE Kinetic Rifle - The range on the rifle is probably a bit long, and the bulk a bit higher. Personally, I think the penetration/damage should be somewhat raised, with the blunt penetration going to around 60ish and the damage going up by one or two points to 11-12 ish.
TE Kinetic Long Rifle - As with other regular TE weapons, I’d like to see an increase in blunt penetration, for the long rifle probably into the ~120-150ish range or so.
TE Thudd Gun/Singularity Projector - I think their current implementation as a CQC/Automatic grenade launcher is largely fine. Apart from merging their ammo, I’d suggest raising their damage just to make their penetration against non-unarmored targets a bit more consistent.
TE Kinetic Lance - Since the damage on this is supposed to be penetrating, it may be required to switch the weapon to dealing damage using direct projectile implementation (like a heat rocket) while keeping a minimal damage blast for aesthetics. I would also significantly raise the penetration value and slightly raise either the burst/ammo count or the damage, as the weapon is supposed to fulfill an anti-armor role akin to conventional launchers, and it kind of is so-so in that role at the moment compared to other available options. I would balance out these changes by bringing in the range to the 30-40ish range (as the vanilla version is actually on the shorter end of ranges at 20), and having it consume a considerable amount of ammo when firing, giving it an economic impact akin to a conventional anti-tank launcher.

GD Weapons - As a whole I’m largely okay with the implementation of Greydale weapons, helped by the fact that they’re generally pretty conventional weapons. It might be worth perhaps shuffling back a few of the weapons tech requirements to prevent the player from having access to what is functionally a 5.56 AR by only doing gas operation + microelectronics, but I think that’s not particularly important. Given that all the modular rifle system weapons are bullpups, they should have the extra 0.5 second reload time
Modular Pistols (Triple shot, Spitfire, Hybrid) - Personally, I’d swap the cartridge to a PDW type one or another one with decent penetration
Modular Carbine/Rifle - I’d either reduce the carbine’s magazine size or increase the rifle’s one, as the rifle has a visually larger mag. I think it may be worth considering reducing the carbine’s warm up to move it into a role similar to the AKS-74U, but I don’t think it’s specifically needed, especially given how early tech-wise it is to access.
Hybrid Weapons - Personally, I think these should have their charge ammo switched out for an ammoset using their conventional rounds, but with increased velocity (and benefits/drawbacks associated with that) as well as slightly increased penetration values, cementing their role as a intermediate step between conventional and charged cartridges.

Side note about the melees: Personally, I’d like to see the vibrodaggers/survival knife/torch sword and Jotun maul moved into the powered weapon tier mechanics wise.

Rimsenal Vanilla - Personally, I think there is very little here I think needs adjustment from its current implementation (outside of protective gear and its insane stats). Key things I’d like to see adjusted are (obviously) just some of the spacer tier equipment.
EMP Rifle - No free lunch, make it use plasma cells (either multiple of them or heavy ones) since it requires charged tech to research anyway. As part of this change however, I’d like to see its bulk decreased a bit ,as well as its warm-up cooldown adjusted to sane values.
Smart Pistol/SMG - I’d like to see these use a caliber that is actually somewhat viable at endgame, considering that they’re competing with Charge SMG/AKS-74U by the time you can make them. I.e. 4.6/5.7 or 7.62x25, pretty much a caliber that isn’t only effective against tribals or nude pirates. Maybe even 4.73x33mm caseless, which does feel very high tech.
Charge Driver - While the mech round is convenient, it does make it too easy to acquire ammo for the weapon. It may be prudent to either introduce a new charge caliber (actually, I’d like to see a magnum/full power rifle/Anti-material (non-mechanoid) caliber for charge weapons in general, but that’s a bit seperate from the patch), or use a altered 8x35mm caliber that increases the velocity and as such, associated damage/penetration.

**Comment by N7Huntsman** [comment]
I'm going to mark this as a draft for the time being. I like some of Tostov's ideas, but they'll take some time to implement and test.

**Comment by N7Huntsman** [comment]
- [ ] Scrap armor, Protective gear, feral exosuit and Pioneer armor are all far too strong for their resource investments.
- [ ] Scrap armor is also stronger and lighter than a steel vest despite being a general downgrade compared to flak vest in vanilla.
- [ ] Protective gear is insanely low impact for how strong it is. For equivalency, for 3 more bulk and 2 less kg of weight compared to plate, you get an apparel that is 6x as strong on sharp protection, 9x as strong on blunt protection, has 10 more HP, is less bulky when not worn. Likewise it weighs the same as a steel vest and provides nearly 2x the sharp protection across all body parts as opposed to torso/neck/shoulders.
- [ ] Feral Exosuit is cheaper and stronger than recon armor. While it does have a global workspeed malus it's still an insanse difference in cost, provides better carry weight and bulk capacity as well. Also the weight is only 18, but I assume that is a missing patch/error there.
- [ ] Pioneer armor once again (though not as much so as the feral exosuit) is cheaper than recon armor and had significanty better sharp protection, exceeding even conventional power armor. It is interesting in that it does have a negative effective weight (since it's heavier than the weight bonus it provides), but honestly of the armors I'd honestly think that assault armor, the one specifically supposed to be slow should be the one to have that property. I think evening out the carry capacity vs weight and toning down the sharp protection back to 17-18 or so would be a better option.
- [ ] 7.62x55mm CC is pathetically weak, to the degree I'd wager that there's a typo in the ammodef.
- [ ] Shard Rifle - Personally, I’d like to see the full auto capacity scaled up from 5 to 6-8sih, as well as the range toned down to probably around 40-44ish to be closer to the other sub-carbines, which it kind of behaves like.
- [ ] Dual Wield pistols - With new ammoconsumedpershot part of the ammouser comp, there’s no reason not to make this just fire a 2 pellet shot and restore it’s full auto capability.
- [ ] Spike Rifle - Ignoring the current ammo stat at the moment, it should really have an extreme amount of penetration for the shot, somewhere in the range of 30-40mmRHA imo. I wouldn’t set the damage too high but the vanilla version is actually only outmatched penetration wise by the JI series of weapons and the anti-material rifle of the vanilla options.
- [ ] Microwave/Nanoswamer/Vector Shot in general - I think these three would benefit from having some sort of universal power cell type ammo that all three share, since they all have very strange weapon setups.
- [ ] Microwave Emitter - I think it would be reasonable to make the damage def for this (and consequently the grenades) apply CE’s muscle spasms hediff for downing targets, as this serves much the same role. The amount applied could be limited, since targeting heat armor makes it effective against a wider range of targets but it should be considered.
Swarmer - Not much to say, I think restoring it to its conventional setup and giving it a fair amount of low damage pellets with lowish spread would be the way to go.
- [ ] Vector Shot - Rather than a half assed SMG, now that we have a precedent to work off of, it should be converted to a short range mortar type weapon with invisible projectile as the original in vanilla functionally is. This can be achieved by giving the projectile a very high gravity factor which allows us to use a fairly high speed projectile to give it minimal travel time.
- [ ] JI Weapons - Personally, I am not a very big fan of how some of the weapons are currently implemented in this patch. In general, I’d like to see them adjusted more towards being high power single shot weapons, especially with the implementation of AP-I rounds in conventional rifles pretty much pushing them out of any niche that the burn + bullet damage that they previously had.
- [ ] JI Molten Rifle/Pistol in general - As noted before, I’d like to see the ammodef for the conventional molten slugs changed to be more akin to a slug specifically rather than a chonky battle rifle bullet. I think maintaining the incendiary effect is quite interesting and isn’t worth removing, but the overall round specifics should be based on a beefier 12 gauge slug.
- [ ] JI Molten Rifle - Matching with the change in interpretation to shotgun, it should have it’s burst/automatic modes changed to match the shot counts for automatic shotguns rather than assault rifle (i.e. 3 on auto, 2 on burst rather than 5/3), assuming it would retain it at all.
- [ ] JI AMR - Ideally could use an increase in damage and blunt penetration buff, giving it something akin to the properties of the 23x75mmR but in AP-I form, but with its current sharp penetration retained.
- [ ] JI Siege Shotgun/Suppressor Cannon - My suggestion would be to merge the ammo type for these two weapons, and use the ammoConsumedPerShotCount to have the siege shotgun fire 4 shots as a spread and the suppressor fire what is functionally the same shot but individually as part of a burst. Part of the idea for this is due to the vanilla suppressor cannon being a lower power/penetration weapon that fires a significant number of rounds, closer in performance to a low RoF Minigun than the single high damage shot profile that all other JI weapons use.
- [ ] JI Siege Cannon - I’m mostly fine with the performance characteristics of the weapon, though I don’t think there’s any need for the weapon to have such a long cooldown/warm-up (4 seconds is absurdly long) or sub 100% sight accuracy.
- [ ] TE Weapons - As a whole I think these could use a bump in their blunt penetration power or in their damage, either cementing their role as a anti-blunt armor specialty weapon with consistent damage, or as a weapon designed to specifically punish low blunt armor levels. I think that as per their descriptions/implementation in vanilla, the kinetic pistol/rifle/long rifle should all be given fairly fast warm-up times for their respective weapon classes akin to the VWE:Quickdraw guns. The semi-energy based nature of the weapons also makes them an ideal candidate for merging all of the ammo into one power cell type munition and using the ammoConsumerPerShotCount part of the verb to differentiate the weapons’ ammo consumption.
- [ ] TE Kinetic Pistol - Given that the functionality of the pistol’s ammo is shared with the rifle’s, and that the rifle ammo should be reasonably strong, I’d suggest giving it a smaller ammo pool, closer to 7-9ish rounds rather than the 12 it has now.
- [ ] TE Kinetic Rifle - The range on the rifle is probably a bit long, and the bulk a bit higher. Personally, I think the penetration/damage should be somewhat raised, with the blunt penetration going to around 60ish and the damage going up by one or two points to 11-12 ish.
- [ ] TE Kinetic Long Rifle - As with other regular TE weapons, I’d like to see an increase in blunt penetration, for the long rifle probably into the ~120-150ish range or so.
- [ ] TE Thudd Gun/Singularity Projector - I think their current implementation as a CQC/Automatic grenade launcher is largely fine. Apart from merging their ammo, I’d suggest raising their damage just to make their penetration against non-unarmored targets a bit more consistent.
- [ ] TE Kinetic Lance - Since the damage on this is supposed to be penetrating, it may be required to switch the weapon to dealing damage using direct projectile implementation (like a heat rocket) while keeping a minimal damage blast for aesthetics. I would also significantly raise the penetration value and slightly raise either the burst/ammo count or the damage, as the weapon is supposed to fulfill an anti-armor role akin to conventional launchers, and it kind of is so-so in that role at the moment compared to other available options. I would balance out these changes by bringing in the range to the 30-40ish range (as the vanilla version is actually on the shorter end of ranges at 20), and having it consume a considerable amount of ammo when firing, giving it an economic impact akin to a conventional anti-tank launcher.
- [ ] GD Weapons - As a whole I’m largely okay with the implementation of Greydale weapons, helped by the fact that they’re generally pretty conventional weapons. It might be worth perhaps shuffling back a few of the weapons tech requirements to prevent the player from having access to what is functionally a 5.56 AR by only doing gas operation + microelectronics, but I think that’s not particularly important. Given that all the modular rifle system weapons are bullpups, they should have the extra 0.5 second reload time
- [ ] Modular Pistols (Triple shot, Spitfire, Hybrid) - Personally, I’d swap the cartridge to a PDW type one or another one with decent penetration
- [ ] Modular Carbine/Rifle - I’d either reduce the carbine’s magazine size or increase the rifle’s one, as the rifle has a visually larger mag. I think it may be worth considering reducing the carbine’s warm up to move it into a role similar to the AKS-74U, but I don’t think it’s specifically needed, especially given how early tech-wise it is to access.
- [ ] Hybrid Weapons - Personally, I think these should have their charge ammo switched out for an ammoset using their conventional rounds, but with increased velocity (and benefits/drawbacks associated with that) as well as slightly increased penetration values, cementing their role as a intermediate step between conventional and charged cartridges.
- [ ] Side note about the melees: Personally, I’d like to see the vibrodaggers/survival knife/torch sword and Jotun maul moved into the powered weapon tier mechanics wise.
- [ ] Rimsenal Vanilla - Personally, I think there is very little here I think needs adjustment from its current implementation (outside of protective gear and its insane stats). Key things I’d like to see adjusted are (obviously) just some of the spacer tier equipment.
- [ ] EMP Rifle - No free lunch, make it use plasma cells (either multiple of them or heavy ones) since it requires charged tech to research anyway. As part of this change however, I’d like to see its bulk decreased a bit ,as well as its warm-up cooldown adjusted to sane values.
- [ ] Smart Pistol/SMG - I’d like to see these use a caliber that is actually somewhat viable at endgame, considering that they’re competing with Charge SMG/AKS-74U by the time you can make them. I.e. 4.6/5.7 or 7.62x25, pretty much a caliber that isn’t only effective against tribals or nude pirates. Maybe even 4.73x33mm caseless, which does feel very high tech.
- [ ] Charge Driver - While the mech round is convenient, it does make it too easy to acquire ammo for the weapon. It may be prudent to either introduce a new charge caliber (actually, I’d like to see a magnum/full power rifle/Anti-material (non-mechanoid) caliber for charge weapons in general, but that’s a bit separate from the patch), or use a altered 8x35mm caliber that increases the velocity and as such, associated damage/penetration.

**Comment by N7Huntsman** [comment]
I've done fairly extensive adjustments, largely along the lines of Tostov's list as shown in the checklist above.
- JI and TE weapons now each have their own universal ammo and with varying `ammoConsumedPerShot` values.
- The Torchsword, vibroblade, and JI hammer are now treated as "powered" weapons, and so are stronger.
- Various tweaks to ammo weight, bulk, protection
- The GD hybrid rifle now uses a custom ammoset, using standard 5.56 NATO, but firing faster, harder-hitting projectiles.
- The EMP Rifle and Microwave Emitter still don't need ammo, mainly b/c it's hard to justify adding a new custom "energy cell" ammo type for each.

**Comment by Tostov** [comment]
JI Assault Armor now has a inbuilt EMP grenade launcher along the same lines as the Royalty grenadier armor that will need to be patched if royalty is installed. Rimsenal removes said launcher comp if royalty isn't installed.

**Review by onigamii — APPROVED** [review]

**Comment by Tostov** [comment]
JI molten ammo (High Density Alloy) requires the siege gun research rather than the inital research, meaning it's possible to make the weapons without the ability to make ammo for them.

**Comment by Tostov** [comment]
Microwave turret top is facing sideways, for some reason. Pretty much it'll look like it's aiming 90 degrees to the left of where it is actually aiming.
Surveillance turret shoots JI molten slugs instead of the TI kinetic shots. (this issue has actually been around for a long time)

**Comment by Tostov** [comment]
Trying to reload the JI rocket turret throws errors, as it has an invalid ammoSet ('Ammo_JIRocket' instead of what it should be, 'AmmoSet_JIRocket')

**Comment by Tostov** [comment]
Guns missing firemode Comps:
Crucible Pistol
Federation snub carbine
Feral Rocket Launcher
JI Siege Shotgun
YP Microwave Emitter

Immediate balance concern:
Current 6mm Railgun is way too strong of a caliber for the modular triple shot.

**Comment by Tostov** [comment]
AD_CruciblePistol is missing a firemode comp.

The two federation turrets (plasma mortar and the laser cannon things in the security tabs) both seem to throw intermittent (but seemingly harmless) red errors related to reloading, presumably because they're turrets with no ammo.

Nest_Missile from security appears to be unable to fire the HEAT missile, throwing an error when it tries to shoot it. HE missile works fine.

**Review by Tostov — APPROVED** [review]
Looks good to go.

**Review by onigamii — APPROVED** [review]

**Pull request merged**
