### PR TITLE
Patch for Vanilla Psycasts Expanded

### PR DESCRIPTION
**Pull request by Airomeda**
## Changes

Describe adjustments to existing features made in this merge, e.g.
- Range adjustment for all psycasts

## Reasoning

Why did you choose to implement things this way, e.g.
- because space magic cool

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

##Issue Notes
- Currently, the Overshield and Guardian Skipbarrier from Protector Psycaster Path, and Shield Animals or even Shrineshield from Wildspeaker Psycast Path are unable to intercept projectiles (in Vanilla they do just fine)

- Warlord's Guideshot Psycast is able to increase ranged weapon's range, but they will remain the same range even if the duration ends unless forced to unequip the weapon to reset their normal range value

### CODE REVIEW

**Comment by owoc** [comment]
Staticlord could use a balance pass since the VE Psycast version is designed around EMP not harming humans, whereas in CE the same EMP inflicts painful burns. As it is a single Ball Lightning can incapacitate an entire humanoid raid in CE.

**Comment by race19991** [comment]
What about making Warlord's Firing Frenzy give a reload speed bonus?

**Comment by Airomeda** [comment]
> What about making Warlord's Firing Frenzy give a reload speed bonus?

good idea, I'm going to add it soon.

**Comment by race19991** [comment]
You are great, btw any idea on why Overshield and  company don't work?

**Comment by Airomeda** [comment]
> You are great, btw any idea on why Overshield and company don't work?

it uses some custom code on the VE side which has yet to recognize our ballistic projectile mechanic, so we need to patch their shield on making them block CE's projectile unlike skip shields psycast which is already patched.

**Comment by MagnusTester** [comment]
Conflagrator tree is really weak in CE due to how CE handles heat armour and pawns being on fire.  I would recommend adding the "prometheum" hediff to some of the attacks, or just allowing them to do direct damage, or maybe even increasing the range of some (breathe fire in particular).

**Comment by Airomeda** [comment]
> Conflagrator tree is really weak in CE due to how CE handles heat armour and pawns being on fire. I would recommend adding the "prometheum" hediff to some of the attacks, or just allowing them to do direct damage, or maybe even increasing the range of some (breathe fire in particular).

you do have point, I didn't factor in heat protection when it comes to conflagration balance tweak. Let me see what I could do on adding prometheum debuff

**Review by N7Huntsman — APPROVED** [review]
Has my nod, though will likely need some work in the future to support some of the other stuff.

**Pull request merged**
