### PR TITLE
Give proper projectile textures to launched grenades

### PR DESCRIPTION
**Pull request by SamaelGray**
## Changes

- What it says on the tin, gave them the proper `LauncherShot` projectile texture.

## Reasoning

- Launched grenades are not beeg boolets.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony (new textures and the changes apply properly)

### CODE REVIEW

**Review by N7Huntsman — COMMENTED** [review]
Honestly, I don't think they different texture is an improvement. It's essentially the same texture but differently proportioned, which makes them look quite a bit too large for the size of the weapon they're being fired from.

**Comment by SamaelGray** [comment]
> Honestly, I don't think they different texture is an improvement. It's essentially the same texture but differently proportioned, which makes them look quite a bit too large for the size of the weapon they're being fired from.

The texture looks different from Bullet_Big, it might look too big in some cases but it makes distinguishing between grenades and other projectiles easier in-game.

**Comment by N7Huntsman** [comment]
I don't think they're _that_ visually different, frankly--at least not in the middle of a firefight. In any event, the drawSize would need to be played with a bit so they appear an appropriate size to the weapon they're firing from--which is probably about the same visual size as when they were using the Big Bullet texture.

**Comment by SamaelGray** [comment]
> I don't think they're _that_ visually different, frankly--at least not in the middle of a firefight. In any event, the drawSize would need to be played with a bit so they appear an appropriate size to the weapon they're firing from--which is probably about the same visual size as when they were using the Big Bullet texture.

I'll figure out the numbers for the drawSizes and we can go from there.

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
