### PR TITLE
Slow projectile tweaks

### PR DESCRIPTION
**Pull request by ItsSamGray**
## Changes

- Increased projectile speed of certain slow moving projectiles such as LV launched grenades and shotgun beanbags
- Added an appropriate gravity factor node to certain slow projectiles like thrown grenades

## References

- In similar vein to https://github.com/CombatExtended-Continued/CombatExtended/pull/1105

## Reasoning

- Some projectiles were left out when certain crude projectile velocities were increased, made the change to bring the ones that were too slow for in-game purposes up to par.
- Gravity factor is added to give the grenades and such a throw arc and lobbing effect to help mitigate the clipping issue that occurs when said grenades are thrown from behind obstacles like chunks

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony

### CODE REVIEW

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
Great Arrows don't need another buff imo. As for beanbag rounds, I'll test them a bit, but they're probably also fine--they shouldn't really be effective beyond 6 - 8 tiles anyway.

**Comment by ItsSamGray** [comment]
> Great Arrows don't need another buff imo. As for beanbag rounds, I'll test them a bit, but they're probably also fine--they shouldn't really be effective beyond 6 - 8 tiles anyway.

it's true that the beanbags have the real world speed in the spreadsheet and ingame, but they are kinda slow in comparison to other slow projectiles that have been sped up. Great arrows are a bit slower than normal arrows shot from shortbows which are even a bit too fast currently, arrows shot from greatbows are a bit slower than the ones shot from recurve bows not by that much that they are currently.

in the end my main purpose for the PR was the grenade speed tweaks, if the arrows and beanbags are not ok to change, we can leave them as is.

**Comment by Tostov** [comment]
Addtional note if possible, since this may have been missed in the first grenade pass, but I'd strongly suggest increasing the gravity factor by an equal amount to both keep the ballistic path of these projectiles, as well as the importance rangefinding has to them. Higher gravity factor also means for a given range the weapons will be shooting more steeply, which makes them a bit more effective at bypassing of shooting over cover, especially for the original grenades that were altered in the previous PR.

**Review by trikanyo — APPROVED** [review]
Changes approved verbally by n7 in #internal

**Pull request merged**
