### PR TITLE
Vanilla Animals Expanded

### PR DESCRIPTION
**Pull request by onigamii**
## Vanilla Animals Expanded

- [x] Arid Shrubland
- [x] Australia
- [x] Boreal Forest
- [x] Cats and Dogs
- [x] Desert
- [x] Extreme Desert
- [x] Ice Sheet
- [x] Livestock
- [x] Tropical Rainforest
- [x] Tropical Swamp
- [x] Tundra

## Notes

- Overall all animals are fairly balanced but i would like to hear opinions on this not really a fan of doing animals.
- **Cats and Dogs** is usable but i feel that the dogs need a major rebalance to be more "realistic", maybe some of the cats too.
- **Australia** adds two new body types for the Platypus and the Kangaroo, didn't touch their part coverage not really sure if i should they all seem relatively similar to CE's.
- I have also modified the Kangaroo's ` baseBodySize ` and ` baseHealthScale ` with the average height of a red kangaroo, there's other animals that i think could get a change too but i'm not really sure, need opinions.

## Testing

- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (playtested over many hundred hours on different colonies)

### CODE REVIEW

**Comment by N7Huntsman** [comment]
I'll take a look through, but the best and easiest reference I can recommend is the AnimalCollabProject integrated patch. It's got a pretty wide array of animals, and they were balanced pretty carefully. If you've got exact duplicate animals in VAE, I personally would say it's perfectly acceptable to just copy-paste from the ACP patch.

Additionally, does `baseHealthScale` affect a pawn's height? I thought only the body size changed that, but could be mistaken.

**Comment by onigamii** [comment]
I've been using ACP as a reference ever since i did the first patch back in 1.0, as for ` baseHealthScale ` i don't really know i had open the wiki on the older repository and it was listed there.

**Comment by N7Huntsman** [comment]
Still need to check through this, but before I forget--please include an update to the SupportedThirdPartyMods.md

**Comment by onigamii** [comment]
Done, added both VAE and VWE that was still missing.

**Comment by onigamii** [comment]
- The Kangaroo doesn't seem to have a Kick attack. Should one be added?
  Technically, AEXP_RearLeftClaws / AEXP_RearRightClaws are the legs.

- Does the Anaconda have some kind of "constriction" attack in VAE?
  Nope, it doesn't.

---

### Changes
- Fixed missing closing brackets
- **Walrus**
  - Changed damage from ` Bite ` to ` Poke ` and labeled it as **Tusks**
- **Alligator**  
  - BITE: ~~0.15 Sharp AP~~ > 3.15 Sharp AP
  - BITE: ~~12 Blunt AP~~ > 15 Blunt AP
- **Artic Coyote**  
  - CLAWS: ~~0.06 Sharp AP~~ > 0.56 Sharp AP  
  - BITE: ~~0.03 Sharp AP~~ > 0.10 Sharp AP 
- **Black Bear**  
  - BITE: ~~31 Power~~ > 22 Power  
  - BITE: ~~8.5 Sharp AP~~ > 6.5 Sharp AP  
  - BITE: ~~25 Surprised Attack Power~~ > 10 Surprise Attack Power
- **Desert Tortoise**  
  - Blunt / Sharp armor ratings now match vanilla tortoise
  - BITE: ~~0.64 Sharp AP~~ > 0.5 Sharp AP
  - BITE: ~~0.5 Blunt AP~~ > 0.700 Blunt AP
- **Hippo**  
  - BITE: ~~5 Blunt AP~~ > 8.5 Blunt AP 
- **Hyena**
  - BITE: ~~0.03 Sharp AP~~ > 1.66 Sharp AP
  - BITE: ~~1.5 Blunt AP~~ > 2.35 Blunt AP
- **Kangaroo**
  - Added ` Blunt ` capacity to AEXP_RearLeftClaws / AEXP_RearRightClaws
- **Moose / Musk Ox**
  - BITE: 0.44 Sharp AP
  - BITE: ~~0.01 Blunt AP~~ > 3.69 Blunt AP
- **Otter**  
  - BITE: ~~0.1 Sharp AP~~ > 1.1 Sharp AP
- **Tiger**
  - BITE: ~~0.4 Sharp AP~~ > 1.35 Sharp AP
  - BITE: ~~2.2 Blunt AP~~ > 2.46 Blunt AP

**Pull request merged**
