### PR TITLE
Update ApexRimworldLegends_Weapons_AssaultRifles.xml

### PR DESCRIPTION
**Pull request by Theblessedwant**
Nerfed Havoc Performance back down to assault rifle levels, Prior ammo had 30mm RHA which was charge lance/blaster levels of penetration, nerfed it to 8x40 Mechanoid Ammo with 16mm RHA penetration

### CODE REVIEW

**Comment by Theblessedwant** [comment]
if anyone has any better ammo to suggest please do

**Comment by SamaelGray** [comment]
You've essentially buffed the weapon, 8x40mm is a magnum charge cartridge (lower power than the manmade 8x50 but still) which deals much higher effective damage/total damage, you should reconsider the change imo.

**Comment by Theblessedwant** [comment]
Noted

**Comment by Theblessedwant** [comment]
instead of changing the ammo which may be quite disruptive, I created a sub thingdef of the 5x35 called low velocity, it uses that ammo and generally has lower stats across the board so it performs more akin to a better charge rifle.

**Comment by SamaelGray** [comment]
Feel free to use the stats from the patch here, it's the 5x35mm Special ammo (low velocity essentially) with proper stats.

https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/Patches/Reinforced%20Mechanoid%202/ThingDefs_Misc/RM_Ammo_Spacer.xml#L194

**Comment by SamaelGray** [comment]
Another alternative would be a low velocity 6x22mm ammo which is made for mech assault rifles, I could provide the proper stats for it if you'd prefer to go that route. Or simply normal 6x22mm but in semi-auto or something although 6x22mm itself without any nerf would be ok too.

**Comment by Theblessedwant** [comment]
> Feel free to use the stats from the patch here, it's the 5x35mm Special ammo (low velocity essentially) with proper stats.
> 
> https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/Patches/Reinforced%20Mechanoid%202/ThingDefs_Misc/RM_Ammo_Spacer.xml#L194

27mm RHA penetration is way too close to the 30mm RHA penetration of the standard 5x35, ive reduced down to 20 to better suit assault rifle/carbine levels of mechanoid weapon performance.
I'd rather use the same 5x35 ammo but use a different projectile/ammoset, it fires the same round albeit slower in nature
I've already created the new ammoset which seems to work as is, It will readily penetrate recon armor but may struggle against higher quality marine armor

**Comment by SamaelGray** [comment]
It's unrealistic and half-assed for 5x35mm a _Concentrated_ charged round to be that slow and have low penetration but you do you. AP is almost linear to velocity and if you want to go from 30 to 20, you'd need to axe one-third of its velocity which would severely impact its damage too which is not reflected in the numbers you've came up with.

**Comment by Theblessedwant** [comment]
Changed it to 6x22 High velocity rounds, should better reflect ammo, sped increased by 50 and rha penetration increased by 5mm RHA

**Comment by Theblessedwant** [comment]
Derped with the xml when changing to 6x22, should be fixed now

**Comment by N7Huntsman** [comment]
Has a rather messy commit history and some other commits I'm not sure are intentional. Probably best to just close this PR and start fresh if we want to continue with the change...

**Pull request closed without merging**
