### PR TITLE
Update Big and Small Patches

### PR DESCRIPTION
**Pull request by ViralReaction**
## Additions

Describe new functionality added by your code, e.g.
- Patch pawnkinds added to Big and Small - Heaven and Hell
- Correct description of armor genes

## Changes

Describe adjustments to existing features made in this merge, e.g.
- Update patches to include new mod names
- Updated ThirdPartySupport list to include changed mod names

## Reasoning

Why did you choose to implement things this way, e.g.
- Satan pawns kinds spawn without weapons. Vanilla rely on talon genes, but that is insufficient due to CE changes to armor system

## Alternatives

Describe alternative implementations you have considered, e.g.
- Leave Satan pawns using talons only:
  - Ineffectual 

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (few minutes to ensure stuff is being patched)

### CODE REVIEW

**Review by SerinaCE — APPROVED** [review]

**Comment by SerinaCE** [comment]
storno, forgot about the loadfolders migration...

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
Holding this PR til the load folders migration is complete to prevent creating conflicts.

**Comment by ViralReaction** [comment]
I’ll rework PR once migration to load folders is complete.

**Review by N7Huntsman — APPROVED** [review]

**Comment by N7Huntsman** [comment]
I've merged this and ported the changes over to the loadfolder version.

**Pull request merged**
