### PR TITLE
Update patch for VFE:Mechanoids 

### PR DESCRIPTION
**Pull request by SaltyKarl**
## Additions

Patch all the new bots mechs and clothes by VFE:M they all work fine
Couldn't get the jumping lighting bolt to work tho, may need to delete the placeholder tesla turret patch I made.

## References

Links to the associated issues, e.g.
- Contributes towards #1197 

## Reasoning

Why did you choose to implement things this way, e.g.

## Alternatives

Describe alternative implementations you have considered, e.g.
maybe leave the tesla turret unpatched.

## Testing

Check tests you have performed:
- [ .] Compiles without warnings
- [. ] Game runs without errors
- [ .] (For compatibility patches) ...with and without patched mod loaded
- [ .] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by ItsSamGray** [comment]
Thanks for the patches.
Maybe fix the attack tools for the riot mech while we're at it?
It is missing blade stab and cut and shield bash tool that it has originally.

**Comment by ItsSamGray** [comment]
Cool stuff indeed.
My humble two cents tho, now that the riot mech ahs the proper tools, maybe make the headbutt attack less damaging?
I'd made a patch for my own use based on scyther's tools, a bit less damage and a bit higher cooldown, I thought it might have been a good basis for balance since the buildable mechs are not as good as the original ones. But at the end of the day I'm not familiar with the balancing standards behind melee attacks since I haven't looked into the spreadsheet.

**Comment by N7Huntsman** [comment]
Hi @SaltyKarl, thank you for submitting that patch! This was on the list of things for the pending release, and your contribution saved us quite a bit of time. The patch itself is generally very well done, but I have a few balancing adjustments to make here and there. I'm going to close this PR, as I've got an updated version in #1207 with the balance tweaks included.

**Comment by SaltyKarl** [comment]
Happy to help.

**Pull request closed without merging**
