### PR TITLE
Gimmicks patch fixes

### PR DESCRIPTION
**Pull request by zozilin**
TheLoneTec#2438 on discord

> hey, i corrected some errors with the gimmicks patch that comes with, its missing a couple items, and some of the nodes were "replace" when they should have been "add" so they were failing or not being fixed. https://pastebin.com/hngKA20y

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

### CODE REVIEW

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
Needs a fix and probably a few stat adjustments. I'll probably just grab the updated patch, make the necessary changes, and add it to my various stuff PR. I'll close this PR once that's taken care of, but thank you for submitting this, Zoz.

**Comment by N7Huntsman** [comment]
I've added these changes plus a few fixes and adjustments to #1309. Thank you for working on this.

**Comment by zozilin** [comment]
👌It's TheLoneTec#2438 from discord who made it

**Comment by Therandus93** [comment]
Hey, yeah i forgot to remove the success tag before it posted it. Also realise i worded it wrong, it was switching PatchOperationAdd for PatchOperationInsert, as equippedstatoffsets doesnt exists for all the tools yet. Feel free to adjust values, i kinda just guessed from vanilla stats. made most things like fan and pillow stuff do basically no damage.

**Pull request closed without merging**
