### PR TITLE
Update Forsakens patches (2 May 2020)

### PR DESCRIPTION
**Pull request by sumghai**
## Changes

- Re-enable Black Hydra weapons patch
  - Patch was previously dummied-out, due to bug in original Forsakens mod where the weapon was defined as a `thingDef` rather than the standard `ThingDef`
  - Original mod was updated on 1 May 2020 with a fix
- Fix missing Forsakens arrow ammo textures

## References

- Fixes outstanding issues from #13

## Reasoning

- Black Hydra weapon stats based on BFG 9000 from CP DOOM mod patches
  - Infinite ammo as per item description in original Forsakens mod
  - Projectile AP and blast damage stats similar to vanilla CE M6 HEAT rockets
  - Replaced `Forsaken.Linking` class from original projectile with `CombatExtended.AmmoDef`, as the former is incompatible with CE (this removes the lightning strike FX, but otherwise does not impact weapons function)

## Testing

Check tests you have performed:
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (30 mins)
  - Verified that Black Hydra weapon spawn and fire correctly with Forsaken NPC faction pawns
  - Verified that Forsakens arrow ammo item textures are displayed correctly

### CODE REVIEW

**Comment by sumghai** [comment]
@N7Huntsman - @Kik0hi has fixed the Black Hydra on his end, and so as promised, I've fixed our patches here.

**Comment by MadaraUchiha** [comment]
Does this supersede #13? Should we close that one in favor of this?

**Comment by sumghai** [comment]
@MadaraUchiha - No, this is a _follow-up_ to #13, which was _already_ merged.

**Comment by MadaraUchiha** [comment]
Right, I got confused with #20, meant to ask if this PR supersedes it.

**Comment by sumghai** [comment]
No.

#20 applies to a separate Forsakens Fauna (animals) mod, whereas this PR is for the original, main Forsakens humanoid alien / faction mod.

**Comment by sumghai** [comment]
Agreed regarding the Black Hydra - I've now significantly increased its warmup and cooldown times.

As for the bow, I'm tempted to keep it at vanilla stats, as it is right now.

**Pull request merged**
