### PR TITLE
[RH2] Rimmu-Nation² - Clothing Armor Patch

### PR DESCRIPTION
**Pull request by ConTacMight**
Adds numerous similar body armors, helmets, equipment and backpacks. This is the patch for armors specifically.
PS: Don't mind "test patch", this was my first time really using GitHub and Visual Studio together. 
## Reasoning

Just copied from previous patch and extrapolated elsewhere. Change whatever.

## Testing

Check tests you have performed:
- [X] Compiles without warnings
- [X] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

### CODE REVIEW

**Review by androsshi — CHANGES_REQUESTED** [review]
- Get rid of the extra files.
- If you're gonna work on more patches, include them all here.

**Comment by ConTacMight** [comment]
> 
> 
>     * Get rid of the extra files.
> 
>     * If you're gonna work on more patches, include them all here.

If you mean the test patch, that should already be deleted. I don't know how to remove it from the commits tracker tho. If there's other files, I don't remember adding anymore other than the patch and that mistake of a starting file. Do you have any tips?

**Review by kbatbouta — CHANGES_REQUESTED** [review]
Please exclude files in the `.vs` folder.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
I'd suggest we get this onto a branch on the main repo so we can get people working on it.

A fine start, but some various things that need changed:
- Gas masks need the appropriate layer and giving them the correct hediff.
- Various apparel needs correct thickness.

**Comment by Breadbox2k19** [comment]
Is patch is still being worked on? It's far from being finished, if it is not. I'll take over.

**Pull request closed without merging**
