### PR TITLE
Added save and load for loadouts

### PR DESCRIPTION
**Pull request by nickweedon**
## Additions
* Added load and save functionality to to the loadout management screen.
* Credit to Kiame Vivacity for the load/save dialog code which I based
  these screens off. This also ensures visual consistency when using his
  great '[KV] Save Storage, Outfit, Crafting, Drug, & Operation
  Settings' mod. 
  _[ Having spoke with KV (and gain his permission to use this code), 
  it turns out these dialogs actually came from the base game but having them
  available in his mod was helpful nethertheless. ]_

## References
- https://github.com/CombatExtended-Continued/CombatExtended/issues/1245

## Reasoning
- In case anyone is curious, I implemented the load/save serialization/deserialization logic separately from the Scribe logic (i first thought that abstracting this would be more maintainable) since the logic is inherently different as not everything is serialized. Secondly the Scribe framework appears to be fundamentally difficult to re-use aside from monkey patching through reflection or something crazy like that. Creating a facade would be a cool idea (pass in a either the 'Scribe' implementation to write to the actual game save file or a separate implementation for writing to loadout configuration save files. This would be immensly over-engineered however.

## Alternatives

- Seems like a fairly simple change, can't think of any glaring alternatives.

## Testing

Check tests you have performed:
- [Pass (no additional warnings) ] Compiles without warnings
- [Pass ] Game runs without errors
- [Pass] (For compatibility patches) ...with and without patched mod loaded => Handles missing ThingDefs
- [Partial ] Playtested a colony: 3 hours so far

### CODE REVIEW

**Comment by zozilin** [comment]
I get a spam of errors if I try to load a loadout with nonexisting items.

I created and saved a loadout with items from Revia and CE Guns mod (Harvester and RPG-7). Then I removed those mods, restarted the game and tried to load that loadout. 

https://gist.github.com/HugsLibRecordKeeper/73da324d2989ade765039a8d413022c5

**Comment by nickweedon** [comment]
This was to be expected as I have not addressed this use case yet (check the discussion where i mentioned this as a known issue). I  will go ahead and add in this validation now.

**Comment by nickweedon** [comment]
OK this issue should now be fix in the with the rebased commit that i just made. It will inform you of which items could not be loaded. I word the message as follows: "The following loadout slots could not be loaded as these things do not exist in this world: thing1, thing2, etc". 
All other valid loadout slots in your loadout will still be loaded.

**Comment by zozilin** [comment]
Nice. A very minor nitpick - is there a way to suppress leftover red errors for missing items when loading a preset?
```
Failed to find Verse.ThingDef named ReviaSerratedScythe. There are 2871 defs of this type loaded.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DefDatabase`1<Verse.ThingDef>:GetNamed (string,bool)
CombatExtended.LoadoutSlot:FromConfig (CombatExtended.LoadoutSlotConfig)
CombatExtended.Loadout:FromConfig (CombatExtended.LoadoutConfig,System.Collections.Generic.List`1<string>&)
CombatExtended.Dialog_ManageLoadouts/<>c__DisplayClass44_0:<DoWindowContents>b__1 (System.IO.FileInfo,CombatExtended.FileListDialog)
CombatExtended.FileListDialog:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

```

**Comment by nickweedon** [comment]
OK, this latest commit removes the erroneous log error. I decided in the end not to log a warning either as ultimately this is a valid use case and there is nothing unexpected in this scenario since the user is informed of the situation directly.

**Review by N7Huntsman — APPROVED** [review]
It'll need a coder to look it over, but it has my approval from the testing side.

Just to ensure we have our bases covered, I'm going to reach out to KV and ensure he's alright with his code being integrated into CE, as it would then fall under CE's license and would be freely use and modify (within the restrictions of CE's existing license). Hopefully, he should be on board with that, but it's best of check.

**Comment by N7Huntsman** [comment]
KV-permission

**Comment by nickweedon** [comment]
Some additional info on the save/load feature:

Save/Load file location

- Windows: %USERPROFILE%\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\SaveStorageSettings\loadout
- Linux: ~/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios/Saves/SaveStorageSettings/loadout
- Mac: ~/Library/Application Support/RimWorld/SaveStorageSettings/loadout

Each saved loadout is saved as a separate file. While the save filename is defaulted to the name of the loadout this can easily be changed in the save loadout dialog.
Note that the loadout save file name may be different to the actual loadout name. Loading a loadout that already exists will cause the loaded loadout to be given a unique suffix as to avoid a collision.

The following example shows the format of a loadout file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<LoadoutConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <label>AP-HE Anti Material Rifle</label>
  <slots>
    <LoadoutSlotConfig>
      <isGenericDef>true</isGenericDef>
      <defName>GenericMeal</defName>
      <count>1</count>
    </LoadoutSlotConfig>
    <LoadoutSlotConfig>
      <isGenericDef>true</isGenericDef>
      <defName>GenericDrugs</defName>
      <count>3</count>
    </LoadoutSlotConfig>
    <LoadoutSlotConfig>
      <isGenericDef>false</isGenericDef>
      <defName>MedicineHerbal</defName>
      <count>5</count>
    </LoadoutSlotConfig>
    <LoadoutSlotConfig>
      <isGenericDef>false</isGenericDef>
      <defName>Gun_RSAMRifle</defName>
      <count>1</count>
    </LoadoutSlotConfig>
    <LoadoutSlotConfig>
      <isGenericDef>false</isGenericDef>
      <defName>Ammo_50BMG_HE</defName>
      <count>40</count>
    </LoadoutSlotConfig>
  </slots>
</LoadoutConfig>
```

Notable fields:
- The field 'IsGenericDef' is a special discriminator to distinguish the defName from a special 'GenericDef' ThingDef type (e.g. "GenericMeal") that could potentially collide with actual regular ThingDef defNames.
- The 'label' field is the actual name of the loadout (can be different from the save file name).

**Comment by zozilin** [comment]
Been playing with it for a couple of weeks, no issues so far

**Review by albertbokor — APPROVED** [review]

**Pull request merged**
