### PR TITLE
Fix pawns firing through wall corners, improve LOS detection

### PR DESCRIPTION
**Pull request by LockdownX7**
## Changes
* Fixed pawns being able to fire through wall corners
* Improved the function that calculates which cells are present along a vector (previous implementation was lighter but missed some cells)

### CODE REVIEW

**Comment by Breadbox2k19** [comment]
Is there any specific tests that you recommend conducting? it is a bit difficult to verify the changes through normal gameplay.

**Comment by LockdownX7** [comment]
The wall corners fix is fairly straightforward to test, you just need to create firing angles that go through the corner edge of two cells. The previous implementation only checked cells that the LOS ray intersects for the purpose of checking obstructions, so in the scenario below, only the two cells to the right of the shooter, and the two cells to the left of the target, were being checked. In the PR, any cells that the LOS ray narrowly touches are now also checked for obstructions, which includes the two plasteel walls in the example, and prevents the shooter from firing through the wall corner.
image

The other change is a bit harder to spot, so you'll want to go into CE mod settings and enable `Draw partial LoS checks` so you have a visual indication of what cells CE is checking for LOS. Essentially, some cells were occasionally missing even though the LOS ray intersects them, and the PR fixes it:
image

**Comment by AluminumAlman** [comment]
> The wall corners fix is fairly straightforward to test, you just need to create firing angles that go through the corner of two cells. The previous implementation only checked obstructions in cells that the LOS ray intersects, so in the scenario below, only the two cells to the right of the shooter, and the two cells to the left of the target, were being checked. In the PR, any cells that the LOS ray narrowly touches are now also checked for obstructions, which includes the two plasteel walls in the example, and prevents the shooter from firing through the wall corner.
> image
> 
> The other change is a bit harder to spot, so you'll want to go into CE mod settings and enable `Draw partial LoS checks` to have a visual indication of what cells CE is checking for LOS. Essentially, some cells were occasionally missing even though the LOS ray intersects them, and the PR fixes it:
> image

Downloaded the branch and built it myself and the results are:
Your fix seems to be for NW, NE, SE, SW directions from both ways, but
image
but the first image's situation's walls don't break LOS,
image
though doing this north to south or south to north does block LOS.
image
The second image's scenario does work as shown.
image

**Comment by LockdownX7** [comment]
Ah, I see the problem. I tested the changes on the bottom left corner of the map where the X and Z coordinates are smaller, but floating-point precision errors start causing issues as the pawns get closer to the top right, which eventually breaks corner detection.

PR has been updated with a fix, @AluminumAlman  can you give it another try and let me know if you spot any more issues?

I'm also including the assembly file here for anyone that doesn't have a C# compiler so you can test the PR if you have time, seeing as the build bot is on vacation.
[CombatExtended.zip](https://github.com/CombatExtended-Continued/CombatExtended/files/6602615/CombatExtended.zip)

**Review by N7Huntsman — APPROVED** [review]
The wall corner fix seems to work as intended. I'd still get feedback from @AluminumAlman regarding the other half.

**Review by MadaraUchiha — APPROVED** [review]
LGTM - Great job!

**Pull request merged**
