### PR TITLE
Update JobDriver_Hunt.cs

### PR DESCRIPTION
**Pull request by eskaggs93**
## Additions

Adjusting the Hunting Algo

## Changes

Deleted some lines and changed the skill threshold

## References

Links to the associated issues or other related pull requests, e.g.

## Reasoning

Why did you choose to implement things this way, e.g.
- I don't like how close pawns get to animals they are hunting, even after the changes it still seems to be too much.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
I'd just reduce the skil level as you have and not change anything else.

**Comment by eskaggs93** [comment]
> I'd just reduce the skil level as you have and not change anything else.

In my play testing, I found I had to remove the additional offset because of how it was coding for short weapon distances. 

The issue isn’t bad for longer range guns, but if you do a tribal start. The limited range of bows causes the pawn to get stupid close all the time. 

Obviously the drawback is it takes an unskilled pawn longer to kill and wastes more ammo. But they trigger man hunter far less often. 

The changes I made basically made the Hunter use max range a majority of the time. 

I did play for probably a 10 hour colony with this starting with bows into guns and didn’t have any issues.

**Comment by LockdownX7** [comment]
> The changes I made basically made the Hunter use max range a majority of the time.

Does this work well when hunting small animals, though? Distance isn't really needed when hunting a squirrel with a bow as it'll usually die or get incapacitated in one hit, firing from max range is just adding a huge time and ammo sink from all the missed shots.

**Comment by eskaggs93** [comment]
> Does this work well when hunting small animals, though? 

Yes it does. The original authors code has a body size factor as a multiplicative. 

The hunters get quite close to small animals. 

And the code above doesn’t run if the manhunter chance is 0.

**Review by N7Huntsman — APPROVED** [review]
It does seems to somewhat improve the ranges at which colonists with decent Shooting are hunting from, but I might recommend setting the skillThreshold to 6 - 8, as I'm unsure if at 5 how effective they are when firing at or near the max range of their weapon when armed with something like a bolt action rifle.

**Review by kbatbouta — APPROVED** [review]
Looks good to me. Tho suggest testers checking if it's balanced by trying to hunt animals that have a none 0 chance of revenge.

**Pull request merged**
