### PR TITLE
Remove the MiddleHead Layer

### PR DESCRIPTION
**Pull request by paradochlorobenzene**
## Changes

Removes the MiddleHead layer and replaces headgear wearable under hats/helmets to either OnHead or StrappedHead.

## Reasoning

MiddleHead is a redundant layer, especially since OnHead and StrappedHead already exists.

### CODE REVIEW

**Comment by N7Huntsman** [comment]
I'm not sure I agree that the layer is "redundant," as it was originally added to mimic the layering arrangement for the body:
onHead = Skin; (e.g balaclavas)
MiddleHead = Middle; (most hats)
StrappedHead = Outer (e.g goggles, gas masks)

**Comment by paradochlorobenzene** [comment]
> I'm not sure I agree that the layer is "redundant," as it was originally added to mimic the layering arrangement for the body: onHead = Skin; (e.g balaclavas) MiddleHead = Middle; (most hats) StrappedHead = Outer (e.g goggles, gas masks)

Well, hats are already covered by the vanilla OuterHead, and pretty sure the only function of the middle layer is to allow people to wear tuques under helmets.

Not sure if that's worth rendering issues.

**Comment by albertbokor** [comment]
> I'm not sure I agree that the layer is "redundant," as it was originally added to mimic the layering arrangement for the body: onHead = Skin; (e.g balaclavas) MiddleHead = Middle; (most hats) StrappedHead = Outer (e.g goggles, gas masks)

It is redundant. Most hats are quite awkward to put other hats on and balaclavas don't need beanies(==other balaclava without the holes) on them.

Is this TF2 or something?

**Comment by albertbokor** [comment]
For some reason I can't find this branch on my side.

**Review by albertbokor — APPROVED** [review]
Yepp, working fine

**Comment by N7Huntsman** [comment]
I'm getting this error:
```
Failed to find Verse.ApparelLayerDef named MiddleHead. There are 12 defs of this type loaded.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DefDatabase`1<Verse.ApparelLayerDef>:GetNamed (string,bool)
System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.Reflection.MethodBase:Invoke (object,object[])
Verse.GenGeneric:InvokeStaticMethodOnGenericType (System.Type,System.Type,string,object[])
Verse.GenDefDatabase:GetDef (System.Type,string,bool)
RimWorld.DefOfHelper:BindDefsFor (System.Type)
RimWorld.DefOfHelper:RebindAllDefOfs (bool)
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()
```

**Comment by albertbokor** [comment]
> I'm getting this error with only CE + Harmony + Core & DLC loaded, but I'm not sure where it's coming from.
> ...

Nope, nothing here.

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
