### PR TITLE
Fix retaliation raids and shelling

### LINKED ISSUE #3419: [Bug]: Making artillery bombardment to any site in temporary map and leave the map before counter action raid arrival
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: latest 1.4 or 1.5, both can reduplicate same bug
Combat Extended version: 15.6.0.0 or older
Combat Extended source (Steam, GitHub, etc.): Steam or from HSK mods pack
Your operating system: Windows
Your mod list:
Harmony
Core
Combat Extenteded

**Description**
Make artillery bombardment (by mortar or so) to any site in any temporary map, until see the message says counter action raid incoming like "A group from Gwowe-Pig is planning to raid NewArrivals soon in retaliation for recent events." , then leave the temporary map before counter action raid arrival. Wait a while, will constantly get errors in a certain frequency. 

**Expected behavior**
IDK, perhaps get caravan caught by ambush incident whom made bombardment while still traveling in world map?

**To reproduce**
Roughly as Description part. 

For example, get into a site with temporary map (e.g. dev action menu → Generate quest... → balablala) , 
图片
图片
spawn some mortar and shells then begin bombardment to any site by gizmo "attack world tile"
图片
图片
till get the message
图片
then just leave the temporary map in whatever ways
图片
then just wait for errors

**Screenshots & log dumps**
图片
图片

I notice that this value change once error pops once
图片

_You can stop error by destroy the site been bombed (whatever dev action menu "destroy site" or in normal way)_

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

### PR DESCRIPTION
**Pull request by mszabo-wikia**
## Changes
As reported in #3419, retaliation raids currently cause infinite error spam if the bombardment that triggered the retaliation was from a temporary map that was disposed of by the time the raid was actually executed. Fix it by checking whether the target map for the raid is actually valid.

While testing this, I found that retaliation shelling has also been broken since d90f3e1395438165e9bade2780299cb2b64b177d. Fix it by accounting for the case where the launcher is not spawned at all, since retaliation bombardment shells are "launched" by world pawns.
Also ensure bombardments from other factions' settlements do not trigger a retaliation
bombardment if the target faction isn't hostile to the owner of the tile,
and introduce a configurable retaliation fire delay that scales with how damaged a
site is.

## References

- Closes #3419 

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony -- triggered retaliation from an event tile, then verified shell behavior and that no errors occur if you leave the map before the raid arrives (as well as that the raid does arrive if you hang around)

### CODE REVIEW

**Comment by mszabo-wikia** [comment]
Here's a test save with everything setup and a retaliation raid + shells already incoming: [temp_map_bomb.rws.zip](https://github.com/user-attachments/files/17534557/temp_map_bomb.rws.zip)

**Review by N7Huntsman — APPROVED** [review]
No longer throws errors when shelling a caravan map that no longer exists.

**Review by MaxDorob — APPROVED** [review]
Looks good

**Review by N7Huntsman — APPROVED** [review]
Bug is fixed, and new shelling behavior is working as intended. We may want to amend the retaliatory raid message to make it clear what map the raid is targeting, but that doesn't need to hold up this PR.

**Pull request merged**
