### PR TITLE
Projectile Impact FX

### PR DESCRIPTION
**Pull request by Breadbox2k19**
## Additions

Standalone code commissioned on the courtesy of Ogliss(supported him on Patreon)

Modextensions that add
-Projectile trail smoke
-Various effect (Smoke puff, spark, explosion motes etc) can be played upon projectile impact.

image
Example of a HE bullet impacting a rock surface, the effect itself is highly customisable via XML. The current effects that are shown here : Yellow spark, small explosion motes and smoke puff.
image
The following effects are achieved via the following Xml additions to the target projectile:
		modExtensions
  li Class="ProjectileImpactFX.EffectProjectileExtension"
                explosionMote>true</explosionMote
                explosionMoteSize>0.5</explosionMoteSize
                explosionMoteDef>Mote_BlastFlame</explosionMoteDef
                explosionEffecter>HEImpact</explosionEffecter
                ImpactMoteDef>Mote_YellowSparkFlash</ImpactMoteDef
                ImpactMoteSize>2</ImpactMoteSize
                ImpactGlowMoteDef>Mote_ExplosionFlash</ImpactGlowMoteDef
                ImpactGlowMoteSize>2.5</ImpactGlowMoteSize
            /li
		/modExtensions

## Reasoning

Because it looks cool and special explosive bullet should you know, explode, when they impact the target.
Imo, impact effects should be implemented for most projectiles(smoke to represent dust being thrown up when bullets hit). But I'm only recommending it for HE bullets for now.

## Testing

Check tests you have performed:
- [ X ] Compiles without warnings
- [ X ] Game runs without errors
- [ X ] (For compatibility patches) ...with and without patched mod loaded
- [ X ] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by Breadbox2k19** [comment]
I've yet to fully explore the full potential of what can the done, but since the code is mostly lifted from the Adeptus Mechanics Armoury mod, one should explore the weapon XML of that mod for examples on what can be done.

**Comment by perkinslr** [comment]
We're not generally in the habit of including compiled assemblies in CE's distribution.  Either it should be added as independent mod, which can then be referenced conditionally on it being loaded, or we should include its source code in CE's Source folder (whether it builds as a separate project or just gets joined with `CombatExtended.dll`).  He sent me the lifted source code for the lasers, but made no mention of this one.  Did he give you a link to the source code?  If not I can inquire.

**Comment by Breadbox2k19** [comment]
> We're not generally in the habit of including compiled assemblies in CE's distribution. Either it should be added as independent mod, which can then be referenced conditionally on it being loaded, or we should include its source code in CE's Source folder (whether it builds as a separate project or just gets joined with `CombatExtended.dll`). He sent me the lifted source code for the lasers, but made no mention of this one. Did he give you a link to the source code? If not I can inquire.

He did, I paid him a commission for the standalone version of both the lasers and projectile FX. Let me know if there's anything you'd like to clarify with/request with him, actually, just message him on discord directly. You have to excuse me as I do not know the source code, he just sent me the dll and what's needed for it to work. 
I do want to see this incorporated as part of the mod so do ask for the source code from him directly.

**Comment by perkinslr** [comment]
> I do want to see this incorporated as part of the mod so do ask for the source code from him directly.

I already did.  It turns out it's a soft dependency of the laser code he gave us.  It *looks* like it's functional; I'll see this weekend about integrating it into our codebase (needs some namespace changes to avoid issues if any other mods adopt it and make local changes).

**Comment by N7Huntsman** [comment]
Definitely an interesting feature, but I'd like to check if there's any kind of performance hit associated with the effects, especially if the rounds are really flying. If there is, I think it'd be preferable to have a toggle in mod settings similar to some other performance-heavy elements.

**Comment by Breadbox2k19** [comment]
I use it and hasn’t really experienced noticeable performance loss, but again, explosive ammunition is relatively rare.

**Comment by N7Huntsman** [comment]
This was incorporated as part of the larger integration of the laser framework, and so the standalone is not necessary.

**Pull request closed without merging**
