### PR TITLE
Preindustrial metallic armors set to steeled material category

### PR DESCRIPTION
**Pull request by albertbokor**
## Changes

patched any preindustrial metallic stuffable armors I've found to use Steeled material category
(searched for "plate", "samurai", "brigandine" and checked relevant VE mods)

## Reasoning

We have `Steeled` material category for a reason. Let's use it and not needlessly gimp NPCs with stupid bullshit like lead or sillver armor.

### CODE REVIEW

**Comment by N7Huntsman** [comment]
I'm against this change, personally. I think the metallic armors provide a bit of oddity and interest flavor, and in many cases their base armor is not _that_ bad, give the fairly low AP of most early melee weapons. Moreover, this change would mean that the armor couldn't be made from other, modded metals unless they have been deliberately patched into the 'Steeled' material.

If the chief concern is the actual protection of these pieces of armor when they're made from these materials, we could evaluate swapping some (0.35 - 1mm) of the material thickness to flat Sharp armor, though this would have its own drawbacks.

**Comment by albertbokor** [comment]
Is there really a point in overcomplicating things and not just, yknow, PATCHING THE THE MATERIALS WE ALREADY PATCH?
Converting the armor values would be a lot more work.
I don't get it?
Why come up with all this sillyness to avoid one simple fix that'd solve the problems?

**Comment by albertbokor** [comment]
Done some testing, apparently useless armors stay below 1/8th of the generated with eiher vanilla and Expanded Materials. 

I'm certain it'll go horibly wrong at some point in the future, but for now, it looks not very signifficant.

**Comment by N7Huntsman** [comment]
No movement on this PR for a while, and it seems like we've roughly reached a consensus that the "exotic" material armors are generating at a low enough rate that they're not meaningfully impact the difficulty of raids. Closing this PR.

**Pull request closed without merging**
