### PR TITLE
Suppression tweaks

### PR DESCRIPTION
**Pull request by AluminumAlman**
## Additions
1. Function to return a 3D vector which if used to trace a shape with vectors of the same length would trace a square instead of a circle;
2. Pawns change remembered suppression location if the local suppression exceeds their suppression threshold;
3. A function to add danger to cells in a radius around a center cell;
4. Debug toggle for displaying cell danger rating;
5. Debug toggle for displaying cell cover ratings for a pawn;
6. Danger multipliers for projectiles and explosions;
7. Fused explosives apply danger to cells after landing and apply suppression to pawns before exploding, with more suppression being applied depending on how close they are to exploding;

## Changes
8. Overhauled how cell cover rating is calculated and how pawns pick cells for running to cover.
9. Projectiles that do no health harm no longer suppress or add danger;
10. Explosives which deal have explosions that deal damage to neighboring cells have an increased suppression and danger applying radius;
11. Projectiles that are lower in height than the wall fill percent apply danger;
12. Fused explosives apply less suppression while in the air;
13. Changed how danger works.

## Reasoning
1. Helpful for detecting cover that is diagonal to the pawn;
2. Helpful for getting pawns to take cover from grenadiers;
3. Used for explosives applying danger to an area;
4. Separated it from the debug display muzzle flash toggle;
5. Was useful for debugging why pawns wouldn't consider going trough doors to take cover;
6. Useful for tweaking pawn reactions to danger;
7. Helps fused explosives to apply suppression, as if having a grenade right next to someone won't have them freak out the longer it doesn't explode;
8. Was necessary to have suppressed pawns act how they do in the video, overall I believe it is now smarter;
9. haha firefoam grenade deal 9999999 suppression;
10. Helps pawns to properly react to that and not stand on the edge of the explosion;
11. Used to be that if the initial projectile height was lower than the wall collision height, then it'd apply danger, this caused projectiles which were flying high in the air to apply danger to cells they travelled trough;
12. Hopefully balances out addition 7;
13. I never realized there was a danger tracker because of how little of an impact it appeared to have on suppressed pawn decision making, now danger from projectiles doesn't decrease the further they travel, as well as tweaked the max danger ticks a cell can have (it may have also been that the danger tracker was broken).

## Testing
- [x] Compiles without warnings;
- [x] Game runs without errors;
- [ ] (For compatibility patches) ...with and without patched mod loaded;
- [ ] Playtested a colony.

## Old additional material
Proof of pawns reacting to stickbombs by running away:
https://user-images.githubusercontent.com/34545746/177002497-2e263045-0197-4131-9742-ce72a8ecfdb2.mp4

Screenshot (this means current behavior might differ) of a pawn reacting to a stickbomb by running away to break line of sight to it:
image

Firefoam grenades dealing suppression before the change:
image

Screenshot (this means current behavior might differ)  of a stickbomb applying danger to an area:
image

### CODE REVIEW

**Comment by AluminumAlman** [comment]
Images of recent addition of displaying cell cover rating for debugging purposes and working pathing behind doors.
image
image

**Comment by ItsSamGray** [comment]
From what I understand, the overall armor value of the apparel that the pawn under suppression is wearing is not taken into account when calculating the amount of suppression they receive.
Pawns in strong/heavier armor should not care about small projectiles and explosions in my opinion.

**Comment by ItsSamGray** [comment]
> > From what I understand, the overall armor value of the apparel that the pawn under suppression is wearing is not taken into account when calculating the amount of suppression they receive.
> > Pawns in strong/heavier armor should not care about small projectiles and explosions in my opinion.
> 
> That means that I'd have to add a stat for average blunt armor, which I recall wasn't well received (by Karim at least, I think).

So how is suppression currently being handled without the changes made in this PR?

**Comment by AluminumAlman** [comment]
> > > From what I understand, the overall armor value of the apparel that the pawn under suppression is wearing is not taken into account when calculating the amount of suppression they receive.
> > > Pawns in strong/heavier armor should not care about small projectiles and explosions in my opinion.
> > 
> > 
> > That means that I'd have to add a stat for average blunt armor, which I recall wasn't well received (by Karim at least, I think).
> 
> So how is suppression currently being handled without the changes made in this PR?

Projectile ticks (moves, checks for collisions, etc.), within that tick checks for people in a 3 tile radius circle, applies suppression to them each separately by deciding whether or not to switch to the explosive case. If it does not switch (is not an explosive projectile), then applies suppression based off of the average sharp armor, the projectile's sharp penetration and damage. If it does switch, then it applies suppression based off of its damage (the explosion damage) with a multiplier of ClampBetweenZeroAndOne(1 - (distanceToPawn/explosionRadius)^2). It also does not check whether or not the damage of the explosive harms health. Then the pawn checks whether or not he has been suppressed by too much. If he has, then he starts crouch walking. Additionally, if a pawn's current cell appears to have a cover rating of 0 or less, then starts checking for nearby cover to run to. If he does find a better cell to run to that has a positive cover rating, then he does run to it. Then checks if his suppression is too high and if it is he hunkers down. If he did not find a better cell, then he hunkers down on the spot if the suppression is too high. That is essentially what suppression does without the PR and still does some things similar in the PR.

**Review by ItsSamGray — APPROVED** [review]
Seems to work as intended in-game as per the intended behavior.

**Review by perkinslr — APPROVED** [review]

**Pull request merged**
