### PR TITLE
Race to the Rim Patch

### PR DESCRIPTION
**Pull request by N7Huntsman**
Patch for the Race to the Rim mod. Patches dragons, their breathe attacks, and the new materials and items added by the mod.

The breathe attacks for a few of the dragons need worked on.

### CODE REVIEW

**Comment by Breadbox2k19** [comment]
I don't see why the dragons can't use the VE verbclass, they are mostly flame attack and should be able to ignore cover most of the time.

**Comment by N7Huntsman** [comment]
Finished, with placeholders for a couple breathe attacks.

**Review by Breadbox2k19 — APPROVED** [review]
Seems good, what does the rebuild assembly mean tho?

**Comment by onigamii** [comment]
> Seems good, what does the rebuild assembly mean tho?

It's something we did for easier testing of PR's that involved changing the source code, and decided to include it for xml PR's too. Easier for people to just download the mod and play if the wish to use a WIP patch.

**Pull request merged**
