### PR TITLE
Patch - AOC The Cleanup Devil

### PR DESCRIPTION
**Pull request by Airomeda**
## Additions

Describe new functionality added by your code, e.g.
- new Ammo
- Animal patches
- Weapon patches
- Apparel patches
- Body Defs patches
- Race patches

## Reasoning

Why did you choose to implement things this way, e.g.
- because yes devil love _cleaning_

## Alternatives

Describe alternative implementations you have considered, e.g.
- no, go get the maid devil **now**

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

## Credits
Thanks to 6shoe for the patch contribution, he's a chad.

### CODE REVIEW

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
I made a couple of small fixes, but what's here generally looks to be in good shape. That said, there are a few things missing: 
- Fireaxe melee weapon
- Traders (need ammo, FSX and Prometheum added as is appropriate)
- NPC pawnkinds need ammo loadouts.

**Comment by N7Huntsman** [comment]
Still to be done:
- A few ranged weapons.
- Traders.
- Pawnkinds,
- Anything else I forgot.

**Review by N7Huntsman — APPROVED** [review]
I need someone else to test the various changes I made, but I think it's all functional.

**Review by N7Huntsman — APPROVED** [review]
I need someone else to test the various changes I made, but I think it's all functional.

**Review by SamaelGray — APPROVED** [review]

**Pull request merged**
