### PR TITLE
Fix More Vanilla Turrets Compatibility

### PR DESCRIPTION
**Pull request by Ano-Nymus**
Removing patch to remove thingCategories from GunComplex. thereby fixing error in Rimworld.

## Additions

None

## Changes

Someone added a patch operation to remove thingCategories from GunComplex.
This causes an error with Rimworld, as it requires minifiable objects to be part of a thingCategories.
Another patch (lines 650 - 669) already replaces the thingCategories, so the faulty operation should be safely removable.

## Reasoning

Removing Console Spam

## Testing

Check tests you have performed:
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (Placed Item)

## Notes

It is unclear as to why the Patch existed, as no other item received such operation.

### CODE REVIEW

**Comment by Ano-Nymus** [comment]
Quick note: The patch at lines 650-669 changes thingClass, not thingCategories, I misread.

The removed patch should still pose no issue, given that other objects are not changed in the same way, 
indicating that the patch itself was a mistake.

**Comment by Ano-Nymus** [comment]
That is strange, as i continue to see the error, No matter the load order.

I only added Harmony, Core, Royality, Mod Manager, CombatExtended and of course More Vanilla Turrets.
All mods are using their respective steam version, but the CE Dev branch shows the exact same error.
Rimworld version 1.1.2654 (64-bit). Linux Version.

Also note that your error is the opposite of mine, i get **"not in any thing category"**:

Config error in GunComplex: is minifiable but not in any thing category
Verse.Log:Error(String, Boolean)
Verse.DefDatabase`1:ErrorCheckAllDefs()
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
Verse.GenGeneric:InvokeStaticMethodOnGenericType(Type, Type, String)
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by Ano-Nymus** [comment]
**Note**:
I could likely add a Patch to catch your error as well, 
but i would really prefer to understand why we are getting different errors first.
What do you think?

**Comment by N7Huntsman** [comment]
I'm going to nix this PR for the time being, since it's still to be determined what, if anything, actually needs a fix here.

**Pull request closed without merging**
