### PR TITLE
Alpha Biomes

### PR DESCRIPTION
**Pull request by Breadbox2k19**
## Additions
Make Tarshell, IED and poison dart CE compatible.

## Reasoning

Why did you choose to implement things this way, e.g.
- Tribals need ways to close distance with pirate raiders
- Smoke bombs allow this while enhancing combat micro
- Thematically appropriate as we already allow tribal prometheum handling
- Easy to implement
- Buffed regular smoke grenades as they are rarely utilized and to justify additional investment

## Testing

Check tests you have performed:
- [ x ] Compiles without warnings
- [ x ] Game runs without errors
- [ x ] (For compatibility patches) ...with and without patched mod loaded
- [ x ] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by Breadbox2k19** [comment]
I couldn't get darts and tarshells to do any damage, is there anything that I should look out for when patching damage?

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
I frankly have no idea how to patch the poison dart for CE, it's special, it has 100% acc unpatched/vanilla, when I patch it, it can be thrown but it does nothing, can't hit anything.

**Comment by Breadbox2k19** [comment]
Basically, what I'm saying is. Darts can't be updated for CE(it is special), the new materials can't be used for weapons so the only patchable thing is the tar shell and IED.

**Comment by N7Huntsman** [comment]
Some of the "fish" have a melee attack, similar to Vanilla Fishing Expanded.
There are a number of materials and leathers that need patched.
The poison dart weapon needs patched.

**Comment by N7Huntsman** [comment]
Submitted a new PR including these files plus the other required patches for the rest of the mod.

**Pull request closed without merging**
