### PR TITLE
Vanilla Weapons Expanded - Heavy Weapons

### PR DESCRIPTION
**Pull request by androsshi**
## Additions
Patch for [Vanilla Weapons Expanded - Heavy Weapons](https://steamcommunity.com/sharedfiles/filedetails/?id=2329126791)

## Notes
- Some stats are just placeholders while proper stats for hip fired weapons are being worked on
- By default all weapons have a mechanic that reduces their hp each shot, since i had to replace their default verb this doesnt work anymore as of now only the Missile Launcher is a one-use weapon.
- Flamethrower works but lacks the fancy graphics, what about the magazine size should i increase it?.
- Ammo some new ammo for the uranium slug (AP / AP-I) not quite sure about the incendiary.

## Testing
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested

### CODE REVIEW

**Comment by Breadbox2k19** [comment]
Tested it, the power armour requirement doesn't seem to work btw.

**Comment by onigamii** [comment]
> 
> 
> Tested it, the power armour requirement doesn't seem to work btw.

It does not but this is somewhat achieved by how heavy / bulky the weapons + ammo are.

**Comment by Breadbox2k19** [comment]
You also need to patch the weapon tag so that non power armoured raider do not spawn with them. Otherwise they’ll appear extremely overburdened, slow and without ammo.

**Comment by Mortagonus** [comment]
Getting error "Attempt to use string Ammouser to refer to field AmmoUser in type CombatExtended.PatchOperationMakeGunCECompatible; xml tags are now case-sensitive. XML: <li Class="CombatExtended.PatchOperationMakeGunCECompatible"><defName>VWE_Gun_SwarmMissileLauncher</defName><statBases><Mass>25</Mass><Bulk>30</Bulk><SwayFactor>1.54</SwayFactor><ShotSpread>0.10</ShotSpread><SightsEfficiency>0.5</SightsEfficiency><RangedWeapon_Cooldown>0.56</RangedWeapon_Cooldown></statBases><Properties><recoilAmount>3.54</recoilAmount><verbClass>CombatExtended.Verb_ShootCE</verbClass><hasStandardCommand>True</hasStandardCommand><defaultProjectile>Bullet_70mmAPKWS_HEAT</defaultProjectile><burstShotCount>18</burstShotCount><ticksBetweenBurstShots>15</ticksBetweenBurstShots><warmupTime>3.5</warmupTime><range>52</range><soundCast>InfernoCannon_Fire</soundCast><soundCastTail>GunTail_Heavy</soundCastTail><onlyManualCast>true</onlyManualCast><stopBurstWithoutLos>false</stopBurstWithoutLos><muzzleFlashScale>12</muzzleFlashScale><targetParams><canTargetLocations>true</canTargetLocations></targetParams></Properties><Ammouser><magazineSize>18</magazineSize><reloadOneAtATime>true</reloadOneAtATime><reloadTime>1.5</reloadTime><ammoSet>AmmoSet_70mmAPKWS</ammoSet></Ammouser><FireModes><aiAimMode>AimedShot</aiAimMode></FireModes><researchPrerequisite>CE_TurretHeavyWeapons</researchPrerequisite><AllowWithRunAndGun>false</AllowWithRunAndGun></li>
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)"

**Review by N7Huntsman — APPROVED** [review]
Good to go.

**Pull request merged**
