### PR TITLE
VPE Shields Compat Code Style Cleanup

### PR DESCRIPTION
**Pull request by N7Huntsman**
## Additions
- Compatibility for VPE shields. Content originally from #2454 was reviewed and tested, moved to a branch for style cleanup.
- Compatibility for shields using the ShieldField comp from VEF.

## Changes
n/a

## References
n/a

## Reasoning
See original PR.

## Alternatives
n/a

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Review by SamaelGray — APPROVED** [review]
In my testing, everything apart from the ShieldField (moving broad shield fields) code used by something like the caretaker mech from RM2 and the Guardian wascasket is patched and working as intended.

**Comment by SamaelGray** [comment]
@MaxDorob Hey, thanks for working on the compatibility code, things are working as intended except the ShieldField code I've mentioned in the message above. Are you interested in taking a look at making that bit of code compatible for CE as well?

image

**Comment by MaxDorob** [comment]
@SamaelGray Sure, i'll check as soon as posible.

**Comment by MaxDorob** [comment]
@SamaelGray Ok, it's done. Check https://github.com/MaxDorob/CombatExtended/tree/VFECore-ShieldField-Compat
image

But there is 2 things:
1. If caretaker moves and shooter staying close then bullet can "pass through" (Cuz shield draw-radius not equals real protection radius):
image
Is it okay?

2. If hit with emp caretaker directly it wont disable the shield . Hitting shield with emp will break it (all the same without CE, so i guess thats ok)

**Comment by SamaelGray** [comment]
> @SamaelGray Ok, it's done. Check https://github.com/MaxDorob/CombatExtended/tree/VFECore-ShieldField-Compat (Branch based on VPE-PR-CodeStyleCleanup branch, so i didn't create a new pull request) image
> 
> But there is 2 things:
> 
> 1. If caretaker moves and shooter staying close then bullet can "pass through" (Cuz shield draw-radius not equals real protection radius):
> 
> image Is it okay?
> 2. If hit caretaker with emp directly it wont disable the shield . Hitting shield with emp will break it (all the same without CE, so i guess thats ok)

Hmm, yea both seem acceptable as they are consistent with the shield's behavior in vanilla.
Thanks

**Comment by SamaelGray** [comment]
Hmm, yea both seem ok as the shields behave the same way in vanilla too.
Thanks.

**Comment by N7Huntsman** [comment]
@MaxDorob Thank you again for your work on getting these shields working. If you interested, you're more than welcome to join the Combat Extended discord (https://discord.gg/ZKsnMpUk). We handle the bulk of the dev communication there, and it's a lot more convenient than github for conversations.

**Comment by MaxDorob** [comment]
@N7Huntsma Feel free to contact with me, i'd be happy to help you to improve CE.
My discord name is _ShaslichnikxP(Макс)#3305_ and I'm a developer (https://steamcommunity.com/id/Shaslichnik100/myworkshopfiles/?appid=294100) , so you may assign me to relevant discord-role 👍

**Review by Thorbane — APPROVED** [review]

**Review by SamaelGray — APPROVED** [review]

**Pull request merged**
