### PR TITLE
Bugfix/#40 emp ammo mechanoid shields

### LINKED ISSUE #40: [Bug]: EMP munitions throw error when hitting mortar/bullet shield.
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.1
Combat Extended version: 1.1.2.0
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windwos 10 x64
Your mod list: Harmony, Core, Combat Extended

**Description**
When hitting a mech mortar/bullet shield from a mech siege, EMP bullets/mortars throw an error when hitting their respective kinds of shields. The projectiles continue through the shield. An EMP rounds affecting the shield generator will temporarily stun it.

This does not occur with non-EMP rounds, which are stopped as intended. 

**Expected behavior**
I'm unsure what the intended behavior is--whether the rounds are just supposed to pass through the shield, or if the EMP round is supposed to stun the shield generator.

**To reproduce**
1. Place mortar or bullet shield using dev mode.
2. Use dev mode to set the mortar to stop non-hostile projectiles.
3. Fire EMP mortar or bullet into the shields area of effect.

**Screenshots & log dumps**
https://pastebin.com/TnsQELzk

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

### PR DESCRIPTION
**Pull request by MadaraUchiha**
## Additions

None

## Changes

- Fixes bug where mortars and EMP ammo would pass through shields and cause an error
- Correctly calculates distance from shield projector, including projectile's height.
- Note that this last one means that it's possible to overshoot a shield entirely, if the projectile's trajectory takes it over the shield and land on the other side.

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #40 

## Reasoning

- Consistent with the rest of our 3D trajectory efforts.

## Alternatives
None

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony (minutes)

### CODE REVIEW

**Comment by MadaraUchiha** [comment]
Ideas for that include:
- Implement a charge system for the shield, depleting with each shot. This allows us to use the projectile's damage (i.e. make mortars do 100HP damage, 12 gauge 5 damage, ion charge 10 damage, etc)
- Make ground projectiles have a set probability of breaking the shield. Say, 20% to break the shield, this will prevent cheesing it by shooting one bullet then opening fire with the rest, and may offer a more realistic feel without much dev time.
  - Variation: probability is some function over the projectile's damage (sigmoid?)

**Comment by N7Huntsman** [comment]
The shield break chance seems to be working as intended.

**Comment by nomoretime0723** [comment]
I have tried it and test the a bit so 1term of testing and there was no error but i specifically tested for “fixes bug where mortars and EMP ammo would pass through shields and cause an error” this part but I couldn't quite understand the next part (Correctly calculates distance from shield projector, including projectile's height.)
But as i said no big red errors

**Comment by MadaraUchiha** [comment]
@nomoretime0723 What it means is that bullets may drop on the shield from above (behaving like the shield is a 3D half-sphere) and not always stop at the circular line (behaving like the shield is a cylinder of infinite height).

What this means in practical terms:
 - You can overshoot the shield. Even if the shield stands between your mortar and whatever you're firing at, you can still hit whatever you're firing at (by shooting at an arc over the shield)
 - Targeting a point inside the shield means that (assuming accuracy) the shot would travel over the shield and get intercepted roughly over your target, rather than get intercepted as soon as it enters the shield radius.

**Comment by MadaraUchiha** [comment]
> The shield break chance seems to be working as intended.

Balance pending, it's currently set to 20% for all ground projectiles, not sure if that's what we want.

**Pull request merged**
