### PR TITLE
Vehicle Framework - Update patch and reference assemblies for 1.5

### PR DESCRIPTION
**Pull request by Rhinous**
## Changes

- Updated the reference assemblies for Smash Tools and Vehicle Framework to latest versions
- ~~Used Harmony Traverses to access the fields and methods that got changed to private in latest VF update~~
- Updated the harmony patch from VehicleStatHandler.ApplyDamageToComponent to VehicleStatHandler.ApplyDamage as latest vehicle framework update made ApplyDamageToComponent a private method called from ApplyDamage
- Updated call to ArmorRating to have the new correct number of arguements

## Reasoning

- Vehicle Framework got updated for 1.5 changing some of the methods and making some of the fields private which broke the CE patch

## Alternatives

- Leave it broken I guess

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony - I've used devmode to spawn some vehicles and shoot them at each other/have raiders shoot at them. Tested with vehicles from RimThunder and Vanilla Vehicles Expanded mods

### CODE REVIEW

**Review by N7Huntsman — DISMISSED** [review]
The AssembliesCore folder doesn't appear to be generating, and when I manually place it there manually, I'm getting this error on start-up: https://pastebin.com/wucS7RAf

**Comment by Rhinous** [comment]
Assuming you meant AssembliesCompat since AssembliesCore is empty/not there in other releases, its disabled in the workflow. Building with dotnet build should work with no issues. Could the AssembliesCompat building be turned back on? I see no real reason why it should remain disabled since CE runs into no issues with them built via dotnet build (even if the patches havent been updated)

**Review by N7Huntsman — APPROVED** [review]
After rebuilding locally, everything works as intended. We may need to confirm the build bot is up to date.

**Review by Thorbane — DISMISSED** [review]

**Comment by perkinslr** [comment]
If I recall correctly, those fields were always private.  When I built the previous reference assembly I publicized the output before including it.  I'm not entirely opposed to using reflection, but it does tend to be more fragile than publicized assemblies, and it is nearly always slower.

**Comment by Rhinous** [comment]
Updated the reference assembly so we don't have to use traverses anymore

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
I get errors every time a projectile or melee attack hits a vehicle. From the looks of it, our armor calculations are running into some trouble. https://pastebin.com/FSp6mpHn

**Comment by Airomeda** [comment]
> I get errors every time a projectile or melee attack hits a vehicle. From the looks of it, our armor calculations are running into some trouble. https://pastebin.com/FSp6mpHn

can confirm I'm facing the same issue, likely to be the Harmony Traverse.

**Comment by Rhinous** [comment]
> > I get errors every time a projectile or melee attack hits a vehicle. From the looks of it, our armor calculations are running into some trouble. https://pastebin.com/FSp6mpHn
> 
> can confirm I'm facing the same issue, I cannot pinpoint where's the source is unfortunately.

I can't reproduce any errors when downloading the latest in this PR from the bot and building with dotnet build (Tried to on a laptop aswell). The only way I can reproduce this error is by loading in the old compatibility patch currently on dev/steam and not in this PR. The error in question is caused by the old patch using an outdated version of the ArmorRating method with only one argument which got updated in the 1.5 version of VF to have 2 arguments and should be fixed [here](https://github.com/CombatExtended-Continued/CombatExtended/pull/3122/commits/2049cceaa4996eacfb3084a1fc0ad61abdfa64c4#diff-49f3e64c62b1e4ca8bcfcb36c6bb4a4ea2090a00775a184cc3e8a8578acbd7f8L275-R280)

**Comment by Airomeda** [comment]
> > > I get errors every time a projectile or melee attack hits a vehicle. From the looks of it, our armor calculations are running into some trouble. https://pastebin.com/FSp6mpHn
> > 
> > 
> > can confirm I'm facing the same issue, I cannot pinpoint where's the source is unfortunately.
> 
> I can't reproduce any errors when downloading the latest in this PR from the bot and building with dotnet build (Tried to on a laptop aswell). The only way I can reproduce this error is by loading in the old compatibility patch currently on dev/steam and not in this PR. The error in question is caused by the old patch using an outdated version of the ArmorRating method with only one argument which got updated in the 1.5 version of VF to have 2 arguments and should be fixed [here](https://github.com/CombatExtended-Continued/CombatExtended/pull/3122/files#diff-49f3e64c62b1e4ca8bcfcb36c6bb4a4ea2090a00775a184cc3e8a8578acbd7f8L275-R275)
> 
> Might need to wait for the bot to have compat assembly building turned back on to make sure its not an issue with how its being built

I've suspected the issue I'm facing with previously could be the latest unstable version of Vehicle Framework I installed from their discord. Just to make sure the Steam version works fine with the current compatibility assembly but it may require changes assuming they changed armor calculation in a stable release approx. around this week.

**Comment by Rhinous** [comment]
> I've suspected the issue I'm facing with previously could be the latest unstable version of Vehicle Framework I installed from their discord. Just to make sure the Steam version works fine with the current compatibility assembly but it may require changes assuming they changed armor calculation in a stable release approx. around this week.
> 
> The Vehicle Framework build version I was using is v1.5.1634 (Unstable) with Combat Extended latest 1.5 Beta build

You were right, the ArmorRating method has been updated again in the unstable branch of VF, I've gone and updated the assemblies since that version is supposed to be going live this week (meaning this PR now requires VF v1.5.1638 or higher)

**Review by Thorbane — APPROVED** [review]

**Review by N7Huntsman — APPROVED** [review]
With the latest VF update, the armor error has resolved.

**Pull request merged**
