### PR TITLE
No stuff4 unfinished arrow

### PR DESCRIPTION
**Pull request by CMDR-Bill-Doors**
## Changes

Remove stuff in unfinished arrow

## Reasoning

So I was told that while making poison arrow (or whatever neolithic ammo with a non-stuff in its ingredients) sometimes an error pops out when that non-stuff was used for the stuff of unfinished ammo. So I got rid of it

## Alternatives

Suffer.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony (15x poison arrow recipe)

### CODE REVIEW

**Comment by SamaelGray** [comment]
Again, please mind the indentation standard just like I commented on #2875. Thank you.

**Comment by CMDR-Bill-Doors** [comment]
> Again, please mind the indentation standard just like I commented on #2875. Thank you.

image
I'm pretty sure it's using tab.

**Comment by SamaelGray** [comment]
The whole CE and its submods are converted to tabs by yours truly, I'm certain these are not tabs.

**Review by N7Huntsman — APPROVED** [review]
No issues in testing.

**Pull request merged**
