### PR TITLE
added various patch for a lot of mods

### PR DESCRIPTION
**Pull request by Airomeda**
## Additions

Patches the following mods:
- Mechanoid Bench 2 [JGH]
- [FSF] More Psycasts Powers
- Infusion 2
- Infused 2 Expansion
- Anima Bionics

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by ItsSamGray** [comment]
Hey, thanks for the infusion 2 patches.
One small nitpick, maybe change the bonus from pocketed and deep pocketed from carry weight to bulk capacity?

**Comment by Airomeda** [comment]
> Hey, thanks for the infusion 2 patches. One small nitpick, maybe change the bonus from pocketed and deep pocketed from carry weight to bulk capacity?

you mean changing the key stats it added? if so I can try to make it does that
or just make it increase carry weight and carry bulk on top of that

**Comment by ItsSamGray** [comment]
> > Hey, thanks for the infusion 2 patches. One small nitpick, maybe change the bonus from pocketed and deep pocketed from carry weight to bulk capacity?
> 
> you mean changing the key stats it added? if so I can try to make it does that or just make it increase carry weight and carry bulk on top of that

Just Bulk should do IMO.

**Comment by Airomeda** [comment]
> > > Hey, thanks for the infusion 2 patches. One small nitpick, maybe change the bonus from pocketed and deep pocketed from carry weight to bulk capacity?
> > 
> > 
> > you mean changing the key stats it added? if so I can try to make it does that or just make it increase carry weight and carry bulk on top of that
> 
> Just Bulk capacity should do IMO.

**Comment by Airomeda** [comment]
> > > Hey, thanks for the infusion 2 patches. One small nitpick, maybe change the bonus from pocketed and deep pocketed from carry weight to bulk capacity?
> > 
> > 
> > you mean changing the key stats it added? if so I can try to make it does that or just make it increase carry weight and carry bulk on top of that
> 
> Just Bulk capacity should do IMO.

yeah I could see it being abused because of the Carry Weight bonus from infusion, like you can infuse 5 apparels with it and that would significantly increase pawn's weight capacity, gotta figure it out first to balance it or rather resort to Bulk increase only

**Review by N7Huntsman — APPROVED** [review]

**Pull request merged**
