### PR TITLE
Militors Balance Adjustments

### PR DESCRIPTION
**Pull request by N7Huntsman**
## Changes
**Militor Mech**
- Reduce the militor's Aiming Accuracy from 1 to 0.6. This is better than the mini-turret (0.25) but worse than the lancer (1.7).
- Reduce the militor's Shooting Accuracy from 1 to 0.769. This gives the militor weapon handling comparable to a (healthy) Level 5 shooter. Previously, it was equivalent to a Level 8 shooter.
- Reduce night vision from 80% (inherited) to 40%.

**Mini-Shotgun**
- Reduced the mini-shotgun's ammo capacity from 8 to 6.
- Increase the mini-shotgun's cooldown from 0.4 to 0.6.

## Reasoning

**Militor Mech**
The militor is a low-tier, swarm-style combat mech. It's patched combat power (60) is equal to a tribal berserker or 1.5 manhunting tortoises. While carrying a shotgun is always going to be an advantage in the early game before armor becomes more of a factor, the militor is currently punching too far above its weight class, with weapon handling equivalent to a better-than-average shooter. 

The 80% night vision it was inheriting from `BaseMech` was likely an oversight, as that's entirely too high for something this cheap to have--especially in the player's hands.

**Mini-Shotgun**
The mini-shotgun still fires 3-inch .410 shells. The 6-round capacity is generous, whereas the 8-round capacity was just too much for such a compact weapon. The cooldown was increased so that the militor can't dump quite as much DPS onto a target.

## Alternatives
- Could leave as-is.
- Could set balance to some other level, such as increasing their combat power.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by SamaelGray** [comment]
I'd leave the accuracy stat nerfs for the militor out, the weapon is being nerfed and it's enough.
https://discord.com/channels/278818534069501953/303988654492090370/1273171742398877757

**Comment by SamaelGray** [comment]
The cooldown of a weapon is representative of its action in CE, a semi auto shotgun is still a semi-auto gun with 0.4s of cooldown so the nerf is unwarranted, the warmup of the weapon is already arbitrarily increases because it can have the wiggle room, if necessary, bump that to 1.1s.

The mech itself is already getting the lowest tier of accuracy among mechs, the nerf is unwarranted same as the trashbin argument, the mech is basic which is already reflected in its stats but not a trashbin. It's a shotgun mech and sure you can spam them but anything is going to become very good if spammed, the player can't even feed the thing ammo-wise if rushed mechtech or starting as a mechanitor from the get-go.

The NV changes can honestly be dropped as it's mostly moot, a shotgun mech doesn't care about the darkness penalty and the base 80% is not gonna end the world.

As for the SB ammoset, the weapon is not snubnose like a revolver and its texture is pretty showing that it has a decently long barrel.

The mag size change is ok imo.

The militor is good, sure, compared to its unlock stage there are much better options for defense then a short range mech, sure it's also expendable but there are turrets that roughly do the same thing. Pegging its combat capabilities is not a logical move no matter how small or big the changes are. Adjust their combatPower or their gestation recipe instead or choose another route.

**Comment by SamaelGray** [comment]
The cooldown of a weapon is representative of its action in CE, a semi auto shotgun is still a semi-auto gun with 0.4s of cooldown so the nerf is unwarranted, the warmup of the weapon is already arbitrarily increases because it can have the wiggle room, if necessary, bump that to 1.1s.

The mech itself is already getting the lowest tier of accuracy among mechs, the nerf is unwarranted same as the trashbin argument, the mech is basic which is already reflected in its stats but not a trashbin. It's a shotgun mech and sure you can spam them but anything is going to become very good if spammed, the player can't even feed the thing ammo-wise if rushed mechtech or starting as a mechanitor from the get-go.

The NV changes can honestly be dropped as it's mostly moot, a shotgun mech doesn't care about the darkness penalty and the base 80% is not gonna end the world.

As for the SB ammoset, the weapon is not snubnose like a revolver and its texture is pretty showing that it has a decently long barrel.

The mag size change is ok imo.

The militor is good, sure, compared to its unlock stage there are much better options for defense then a short range mech, sure it's also expendable but there are turrets that roughly do the same thing. Pegging its combat capabilities is not a logical move no matter how small or big the changes are. Adjust their combatPower or their gestation recipe instead or choose another route so that the situation does not become another 'suppressive HCB' aka tunnel vision one.

**Comment by MaxDorob** [comment]
> The cooldown of a weapon is representative of its action in CE, a semi auto shotgun is still a semi-auto gun with 0.4s of cooldown so the nerf is unwarranted, the warmup of the weapon is already arbitrarily increases because it can have the wiggle room, if necessary, bump that to 1.1s.
> 
> The mech itself is already getting the lowest tier of accuracy among mechs, the nerf is unwarranted same as the trashbin argument, the mech is basic which is already reflected in its stats but not a trashbin. It's a shotgun mech and sure you can spam them but anything is going to become very good if spammed, the player can't even feed the thing ammo-wise if rushed mechtech or starting as a mechanitor from the get-go.
> 
> The NV changes can honestly be dropped as it's mostly moot, a shotgun mech doesn't care about the darkness penalty and the base 80% is not gonna end the world.
> 
> As for the SB ammoset, the weapon is not snubnose like a revolver and its texture is pretty showing that it has a decently long barrel.
> 
> The mag size change is ok imo.
> 
> The militor is good, sure, compared to its unlock stage there are much better options for defense then a short range mech, sure it's also expendable but there are turrets that roughly do the same thing. Pegging its combat capabilities is not a logical move no matter how small or big the changes are. Adjust their combatPower or their gestation recipe instead or choose another route so that the situation does not become another 'suppressive HCB' aka tunnel vision one.


https://github.com/user-attachments/assets/5db4fd45-6d64-44bb-9d86-883d01980c2f
Zero misses at maximum range, ain't they accurate much then needed?
One militor destroyed my 3 pawns (one of them was 14lvl shooting and wasn't able to even hit that militor)
image

**Comment by N7Huntsman** [comment]
>Alright, after some further research, I'm going to switch the mini-shotgun back to the regular velocity .410 ammo.
I'm guesstimating a roughly 14" barrel on the mini-shotgun, since this is a somewhat "typical" size for real mini shotguns and justifies giving it a 6 round capacity (if we got much shorter, we're probably looking at a 3-round cap). With comparisons of the Mossberg Shockwave (14" barrel) to Mossberg 500 (20.5") in 12 gauge (couldn't find useful info for .410), the latter has only about 6% less muzzle velocity. Given that our .410 short barrel is stat'd with almost 30% less, switching takes us too far in the other direction.

**Review by ViralReaction — APPROVED** [review]
Accuracy changes are hard to visual on Buckshot, but many more misses with Slugs/Beanbag. Lower magazine amount and longer before each shot definitely makes them less lethal prior to decent armor.

**Pull request merged**
