### PR TITLE
Add new calibers + some additional multi-caliber compatibility

### PR DESCRIPTION
**Pull request by S1ippinJimmy**
## Additions
Adds a bunch of new calibers.

## Changes
- .17 HMR (an extremely fast and mean cartridge despite being so lightweight - very iconic.)
- .22 Hornet (old school powerful .22 cartridge that was used in US military issue survival rifles in the 20th century, but still somewhat popular.)
- .22 WMR (common in hunting and sporting historically, now also pretty widely used in handguns and semi-auto carbines/rifles, like the Kel-Tec PMR-30.) 
- .38 Super (technically just a more powerful .38 ACP, but the rounds tend not to be interchangeable both ways from what I can find online. It's a pretty popular chamber for 1911 variants and sporting pistols.)
- .38/200 S&W (or just .38 S&W Short, but with this designation to separate it a little bit ingame. Was used a lot in turn-of-the-century police revolvers, as well as the later Webleys and Enfield No2.)
- .41 AE (iconic for being a failed attempt to emulate .40 S&W that never took off, but still ended up being used in quite a few different weapons.)
- .41 Magnum (the somewhat obscure middle child between .357 and .44, but still used in a few different guns, even a Desert Eagle variant.)
- .44 S&W Special (fairly common police/civilian revolver cartridge in the early 1900s, and is the equivalent to .38 Special for .44 Magnum in modern weapons.)
- .45 Schofield (common wild west revolver cartridge, also usable in everything that shoots .45 Colt, .454 Casull, & .460 SW)
- .45 Win Mag (one of the more common "other" semi-auto magnum cartridges in pistols like the Wildey and LAR Grizzly, for fans of guns other than the Deagle.)
- .480 Ruger (another big bore revolver cartridge in the vein of .460/.500 S&W that still gets used in Ruger's bigger guns.)
- .500 Bushwhacker (only used in BFR revolvers but it's absurdly powerful.)

- .243 Winchester (a very popular hunting rifle cartridge that shoots extremely fast, and sits between the .223 and .308 in general performance.)
- .30-30 Winchester (it's the most common lever-action rifle cartridge ever, surprised it isn't already implemented.)
- .38-55 Winchester (another popular lever-action rifle cartridge, closer to .45-70 in performance but generally meant for the lighter lever actions.)
- .450 Bushmaster (a pretty common "high power" cartridge for AR15s during the era where everyone was obsessed about .223/5.56 not having enough stopping power.)
- .458 SOCOM (similar to the .450 Bushmaster, it was pretty iconic for a time.)
- .50 Beowulf (same track as the .450 & .458 but using the biggest and heaviest bullet of them all. Had a big internet presence for a long time.)
- 7mm-08 Remington (a reasonably popular hunting rifle and AR-10 cartridge for those that don't wanna be mainstream and use a .308)
- 8x50mmR Mannlicher (added on request, but it was the staple military cartridge of Austro-Hungarian forces during the end of the 19th century through WW1, and also saw some WW2 use.) 

- Also added a .44 Magnum "Revolver" def that chambers .44 Special (separate so that it wouldn't affect the balance by default), as well as a .460 Def that shoots all of the smaller .45 cartridges, and similarly done for .454 Casull and .45 Colt.

## References
https://docs.google.com/spreadsheets/d/1qy4M8YHhX4RLEYH2BDIbSIC89ho5Got_4XvmWXaXrlk/edit?usp=sharing

Added doc notes to provide sources where info is relevant.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

### CODE REVIEW

**Comment by SamaelGray** [comment]
Marked as a draft for now, needs cross referencing.

**Comment by N7Huntsman** [comment]
Thank you for putting all of this together. A number of the calibers are likely going to be quite useful, but there are I don't know if they'll be useful to add. I've put my thoughts below.

I don't think the following rounds are worth merging:
- **.500 Bushwhacker:** It's a wildcat round that's only made by a single company and only fires from the BFR, while the BFR can be chambered in several other, more common calibers.
- **.38 Super:** It's basically just .38 ACP P+, but one that doesn't work in the most common pattern of pistols chambered in .38 ACP (1900/1902 pattern). Seeing as we only have two weapons that use normal 38 ACP (and their use of it is questionable...), I don't think .38 Super is likely to see any use.
- **.41 AE:** Another wildcat that has seen a few weapons chambered for it, but hasn't seen much widespread use anywhere--and honestly, players aren't going to want a sub-caliber for the Desert Eagle, they'll want the full-power .50 AE.
- .**41 Magnum:** Similar to the above. It wasn't even popular or commercially successful in real life--I don't imagine we'll find any more use for it on the Rim, unfortunately.
- **.45 Win Mag.:** With a strong similarity to the .45 ACP and no common pistols that were chambered for it even when it was invented, I don't see an application for it.
- **.480 Ruger:** As in real life, it sits uncomfortably between .460 S&W (which is more interchangeable) and .500 S&W (which is more powerful), so really lacks an application with those two options available.
- **7mm-08 Rem:** As you observed, it's really just a slightly necked-down .308 mostly for hunting purposes. It performs (at least from CE's point of view) very similarly to 7.62 NATO, and since we don't see many dedicated civilian hunting rifles in mods, we probably don't have a useful application for it. 

Other remarks:
- .17 HMR, .22 WMR, and .22 Hornet should be moved to the Rifle category.
- .450 Bushmaster, .458 SOCOM, and ,50 Beowulf all occupy a very similar role--that being, a high-caliber round for modified AR-15/M4 platforms--so it probably wouldn't hurt to get rid of at least one to avoid needless duplication. I'd suggest ditching .450 Bushmaster, since the other two are rounds designed for military applications.

**Comment by S1ippinJimmy** [comment]
I agree on most points, though I have two disagreements - .38 Super being included as its own cartridge is precisely because .38 ACP's use cases are so limited and the rounds are not interchangeable (it won't safely shoot out of an M1900/1902, and likewise most guns meant for the .38 Auto +P won't cycle using a lower power round.) On it's own, .38 Super is used in a lot of handguns, and also even some SMGs and machine pistols. 

I'd also argue for .500 Bushwhacker simply for that fact that it far surpasses any handgun calibers in CE, even the .500 S&W only has 70% the damage. It's like the .950 JDJ - kind of a meme and definitely proprietary, but it is notable for its performance.

**Comment by SamaelGray** [comment]
Protected branch, will be reopened in a new PR.

**Pull request closed without merging**
