### PR TITLE
Added support for Genetic Rim+Genetic Rim Alpha Animal Patch 

### PR DESCRIPTION
**Pull request by Breadbox2k19**
## Additions
Supports for all vanilla Genetic Rim animals+Alpha Animal Hybrids, including any new weapons, materials and implants. Further tweaks might be added in the immediate future.

## Testing

Check tests you have performed:
- [ x ] Compiles without warnings
- [ x ] Game runs without errors
- [ x ] (For compatibility patches) ...with and without patched mod loaded
- [ x ] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by N7Huntsman** [comment]
I'm getting a number of errors on start-up.

https://pastebin.com/XXxAxTfX

**Comment by Breadbox2k19** [comment]
I'm getting no errors on startup after the tweaks, I'm not getting the

BodyPartRecord with null def. body=GR_Arachnid
and missing leg attack group like you are.

**Comment by Breadbox2k19** [comment]
Seriously, If there’s any problem let me know.

**Comment by Tostov** [comment]
Inbuilt weapons that deal direct damage all throw logging errros whenever they hit something. Afaik, the source of the issue is being looked into at the moment.

**Comment by onigamii** [comment]
Just a test don't mind

**Comment by N7Huntsman** [comment]
Everything seems to be in order. The mods will need to be added the Supported list, though.

**Comment by Dreomite** [comment]
I'm getting
```
BodyPartRecord with null def. body=GR_Arachnid
```
as well.

GenericRim developer [said](https://steamcommunity.com/workshop/filedetails/discussion/1113137502/1480982338961938598/?ctp=14#c3880365909920020922)

> `GR_Arachnid` doesn't exist in Genetic Rim, the mechaspider uses the `BeetleLikeWithClaw` body from vanilla insectoids

The user that reported it also [posted](https://steamcommunity.com/workshop/filedetails/discussion/1631756268/2793873197761411883/) a bug report in CE Workshop discussions.

**Pull request merged**
