### PR TITLE
Patch SCP mod

### PR DESCRIPTION
**Pull request by N7Huntsman**
Patches the apparel, factions, and new SCP 939 creature. Nothing fancy--gear is in line with other RN gear, and 939 has stats similar to a bear.

Closes #449

### CODE REVIEW

**Comment by onigamii** [comment]
There is also the version that only adds the apparels could include it in there too.

**Comment by N7Huntsman** [comment]
> Might be worth including the version that only adds the apparel (also by ods) `SCP - Clothing Only`

There's already a separate integrated patch for that, actually. I glanced at it before I started this patch, but it uses different defNames on everything.

**Comment by onigamii** [comment]
> > Might be worth including the version that only adds the apparel (also by ods) `SCP - Clothing Only`
> 
> There's already a separate integrated patch for that, actually. I glanced at it before I started this patch, but it uses different defNames on everything.

That's actually the old mod, new one is this https://steamcommunity.com/sharedfiles/filedetails/?id=2096995044

**Comment by N7Huntsman** [comment]
Added outfits to the patch operation, though the workshop version is 1.1.

**Review by onigamii — APPROVED** [review]
Everything looks fine

**Pull request merged**
