### PR TITLE
Patch Vanilla Factions Expanded: Pirates

### PR DESCRIPTION
**Pull request by N7Huntsman**
## Additions
- Patches Vanilla Factions Expanded: Pirates

## Reasoning
Warcaskets are essentially a lower-tech hybrid of power armor and mech suits. They're bulkier and slower, but offer comparable or better protection as compared to power armor, at the cost of being extremely impractical outside of combat. Balance-wise, I figured they'd be reasonably vulnerable to fire (as flaming liquids easily poor in gaps and the like in relatively poorly-sealed armor) to offset the advantage of high armor values. 

**Note:** The Gauntlet drop-shuttle used by raiders uses a custom ThingClass, that isn't currently supported. As such, the Gauntlet turret behaves like a vanilla turret and isn't fully patched for CE

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by ItsSamGray** [comment]
12x65 charged for the gauntlet charge cannon?
Isn't 12x64 the correct one? I'm not seeing any 12x65 ammo type in the ammo defs.

**Comment by ItsSamGray** [comment]
I proposed switching from 20mmNATO to 20mmHispano to reduce on ammo type bloat, since the autocannon turret is using 20mmHispano. Maybe it might be a good time to reconsider what the autocannon turret and uranium slug use as ammo, switch the slug turret to 30mm and the autocannon to 20mmNATO for consistency's sake. Redo the ammo types on VWE-Heavy Weapons while we're at it.

**Review by Theblessedwant — APPROVED** [review]
Works on my end

**Comment by Theblessedwant** [comment]
One thing of note, VFE pirates has its own patch, so CE should be loaded AFTER VFE pirates in order to remove a small error. It patches over a def that CE patches over.

**Review by ItsSamGray — APPROVED** [review]
Looks good to me and the problematic turret is fixed with a temporary measure

**Pull request merged**
