### PR TITLE
Alpha animals lost patches

### PR DESCRIPTION
**Pull request by Breadbox2k19**
## Additions
Missed out on the range attack of Erin.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
The projectile throws an error when it fires. The ranged attack works fine when it swapped to a different projectile, but I'm not certain why it's not being patched correctly. Looks like the projectile be alright...

**Comment by Breadbox2k19** [comment]
> The projectile throws an error when it fires. The ranged attack works fine when it swapped to a different projectile, but I'm not certain why it's not being patched correctly. Looks like the projectile be alright...

Hmm, how does the acidic vomit range attack behave without patching? Is it like a vanilla expanded flamethrower attack or is it exactly like a regular, direct impact projectile?

**Comment by Breadbox2k19** [comment]
> The projectile throws an error when it fires. The ranged attack works fine when it swapped to a different projectile, but I'm not certain why it's not being patched correctly. Looks like the projectile be alright...

Anyway, I've tried fixing the attack let me know if it works or looks off. Can't test it personally rn.

**Comment by Breadbox2k19** [comment]
Changed the patch operation for gallatross around to prevent it from throwing errors.

**Review by N7Huntsman — APPROVED** [review]
Erin vomit ranged attack now works.

**Pull request merged**
