### PR TITLE
Incremental reloading for turrets

### LINKED ISSUE #174: [Discussion]: Allowing pawns to reload turrets with very high ammo capacities
<h2>Premise</h2>

Most machine gun turrets in CE have their ammo capacity capped below 600 rounds, which is appropriate for their rate of fire.

For miniguns, rotary cannons and other machine guns with very high rates of fire, this 600 round limit means they require much more frequent reloads than their real-life versions, even when taking into account that turrets in RimWorld are (typically) used against human-sized targets:

Weapon | Source Mod | Caliber | Cyclic RPM | Theoretical CE snap/aimed burst shot count | Actual CE snap/aimed burst shot count | Magazine size <br> (real life) | Magazine size <br> (CE)
-|-|-|-|-|-|-|-
M134 Minigun | Defensive Machine Gun Turret Pack | 7.62×51mm NATO | ~6000 | 300 / 150 | 100 / 50 | 3000~4000<sup>1</sup> rds | 500 rds
Avenger Turret <br> (GAU-8 Avenger) | Turret Collection | 30×173 mm | 3900 | 100 / 50 | 20 / 10 | 1350<sup>2</sup> rds | 100 rds
Gatling Gun Turret <br> (M61 Vulcan) | Turret Collection | 20×102 mm | 6000 | 200 / 100 | 40 / 20 | 1100<sup>3</sup>~1550<sup>4</sup> rds | 200 rds

<sup>1</sup>Typical ammunition box sizes for air/surface applications offered by Dillon Aero, which manufactures the M134 Minigun
<sup>2</sup>A-10 Thunderbolt II
<sup>3</sup>M163 Vulcan Air Defense System (VADS) armored vehicle
<sup>4</sup>Phalanx CIWS or Land-Based Phalanx Weapon System

<h2>Current Issue</h2>

As of CE v2.2.1, if a turret has a capacity above 600 rounds, pawns will often get stuck in a loop trying to reload said turrets.

I suspect that this issue arises from the current behavior behind turret loading in CE - namely, every time a partially-depleted turret is reloaded, the pawn removes the existing ammo first, then (if the existing ammo is the same type as the ammo carried by the pawn) the stacks are merged in the pawn's inventory before being fully reloaded back into the turret. It seems that if the merged stack is greater than the pawn's intrinsic bulk / mass capacity, the pawn is unable to perform a full reload, causing the loop.

To compensate for this turret loading limitation, minigun weapon patches have been forced to use lower burst shot count and magazine capacity values than what is theoretically calculated using the standardized CE spreadsheets.

<h2>Possible Solutions</h2>

- When reloading turrets, have pawns temporarily ignore inventory bulk / mass limits?
- Allow pawns to reload partially-depleted turrets piecemeal without exceeding their inventory bulk / mass limits? (if the reloading involves changing ammo type, the old ammo should be extracted and dumped on the ground, rather than put back into the pawn's inventory)

### PR DESCRIPTION
**Pull request by LockdownX7**
## Additions
- Implement incremental reloading for turrets.

## References
- Closes #174 

## Notes for reviewers
While the PR is intended to only allow turrets to be reloaded in batches, changes have been made in parts of the code that all ammo-using weapons use, so testing should cover these to ensure nothing unintentional is happening when reloading them. The classes of weapon that should be checked are:

- Auto-turrets
- Manned turrets
- Handheld magazine guns (e.g: rifles)
- One-at-a-time reloaders (e.g: Mossberg shotgun)
- Single-shot weapons (e.g: Inferno cannon)

What to look out for:
- Magazine round count is correct throughout the reload process (the mag doesn't end up with more or less rounds than it should)
- Inventory/dropped ammo count is correct when unloading or switching ammo types
- Auto-turrets should not be able to continue acquiring targets and firing after a reload starts, and should immediately resume activity when reloading finishes
- Test turret reloading with ammo system disabled

## Testing
- [x] Compiles without warnings
- [x] Game runs without errors
- [ ] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by sumghai** [comment]
Playtesting feedback:

**Stock CE Heavy Auto-turret (for baseline / regression testing) **
 - Pawn is able to reload or change ammo type from a fully or partially empty magazine

**M134 Sentry Gun from Defensive Machine Gun Turret Pack**
 - Existing patch modified locally to ideal values from #174 
 - Pawn is able to reload or change ammo type from a fully or partially empty magazine
    - Pawn incrementally reloads 7.62x51mm NATO ammo in groups of up to 750 rounds, which is presumably Core's carrying capacity limit (deemed as acceptable)

**Gatling Gun Turret from Turret Collection**
 - Existing patch modified locally to ideal values from #174 
 - Pawn is able to reload or change ammo type from a fully or partially empty magazine
    - Pawn incrementally reloads 20x102mm NATO ammo in groups of up to 750 rounds, which is presumably Core's carrying capacity limit (deemed as acceptable)

**Avenger Turret from Turret Collection**
 - Existing patch modified locally to ideal values from #174 
 - Pawn is able to reload or change ammo type from a fully or partially empty magazine
    - Pawn incrementally reloads 30x173mm NATO ammo in groups of up to 150 rounds, which is that particular ammo's maximum stack size as defined in CE 

**Other Observations**
 - Turrets do not fire while being reloaded (as expected)
 - When changing ammo type, the old ammo is dumped around the turret in its entirety (deemed as acceptable)

All in all, this turned out great! Feel free to do whatever optimization or further regression testing that is needed, but for the most part I'm happy with this implementation.

**Comment by LockdownX7** [comment]
Yes, the limit you're seeing is because of Core: the cap is CarryingCapacity's defaultBaseValue (75), multiplied by 10 because ammo items have smallVolume=true, resulting in 750 (assuming no other modifiers like injured arms). It's not specific to reloading jobs, you'll notice it too while hauling ammo from one stockpile to another.

**Comment by N7Huntsman** [comment]
This PR will sit for today's release, both so it can get further testing and b/c there are currently no turrets with huge mags to benefit from it anyway.

**Comment by sumghai** [comment]
> b/c there are currently no turrets with huge mags to benefit from it anyway.

This may be true for stock CE turrets, but as per my testing above, minigun turrets from the following mods would definitely benefit from increased turret mag capacity and incremental loading:
* DMGT
* Turret Collection
* Rimmu-Nation Security (not yet patched).

Once this PR is approved post-2.2.2, I will update the patches accordingly.

**Pull request merged**
