### PR TITLE
Call of Duty: Zombies Pack Patch.

### PR DESCRIPTION
**Pull request by Robotrowful**
## Additions

Zombies Pack patch whilst patching itself will include patches for smaller individual unreleased patches, These smaller mods have the same Defs will function if someone where to chose all of just one them.
-  Call of Duty: Mystery Box
-  Call of Duty: Pack A Punch
-  Call of Duty: Wonder Weapons

**I am unsure how to balance weapon damages / stats outside of creating Pack a Punched weapons / Bullets and Persona Weapons** (This is becuase those are percentage based increases) 

## References

- Closes https://github.com/CombatExtended-Continued/CombatExtended/issues/1537

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [ ] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

### CODE REVIEW

**Review by ItsSamGray — CHANGES_REQUESTED** [review]
I'd suggest _not_ adding the new ammo types into the CE's main ammo folder, it's pure clutter that is only used by one mod.
You can patch them in when the mod in question gets loaded.

**Review by N7Huntsman — COMMENTED** [review]
These patches are massive and, frankly, the files will need to be consolidated, as each PatchOperation has a loadtime cost associated with it.

For starters, the projectiles really should be in the same file as the ammo and recipe defs. Additionally, they'll need to be assigned a `defName`, as just having a `Name` won't work for the purpose of assigning them. What's the purpose of the "punched" ammo? What weapons use it?

Likewise, the files for the weapon melee tools should go into the same file as the weapon prices.

**Comment by Robotrowful** [comment]
> These patches are massive and, frankly, the files will need to be consolidated, as each PatchOperation has a loadtime cost associated with it.
> 
> For starters, the projectiles really should be in the same file as the ammo and recipe defs. Additionally, they'll need to be assigned a `defName`, as just having a `Name` won't work for the purpose of assigning them. What's the purpose of the "punched" ammo? What weapons use it?
> 
> Likewise, the files for the weapon melee tools should go into the same file as the weapon prices.

I'll try to condence the files as much as possible, when i get the chance.

For the "punched" ammo
With how the mods works several weapons get an upgraded version (actually more than half of all the weapons) that increase it's bullet damage, so if you upgraded version of the pump shotgun the buck would do 16 damage instead of the normal 8. I dont know if it is possible for a weapon to have that function. so I made punched ammosets

the original idea was just several of the weapons for example blundergat, acidgat, magmagat and their upgraded versions sweeper, Vitriolic and Operandi all use just one reloading item but all shoot different bullets. this is the main reason why there is alot of unnessassary bloat for this patch.

**Comment by SamaelGray** [comment]
Due to not having write access to the branch/repo of the PR, will close and reopen it.

**Pull request closed without merging**
