### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by BRLWK**
## Additions

-2 new calibers.
-Patch UWC to use CE's mechanics
-2 new weapons using attachments

## Reasoning
- I would like to make my mod CE compatible  

## Testing

- [X] Compiles without warnings
- [X] Game runs without errors
- [X] (For compatibility patches) ...with and without patched mod loaded
- [X] Playtested a colony (specify how long)
2-3 year colony on 1.4, previous versions longer.

### CODE REVIEW

**Comment by perkinslr** [comment]
Usually, the ammo gets added to CE unconditionally, that way if multiple mods decide to use the same caliber, they don't add duplicate ammos.  You can have a per-mod custom ammoset to go with it, to have control over the damage done.  That part can live in our repo under a patch, or in your own mod as a patch.

**Comment by BRLWK** [comment]
In the repo sounds good, is there anything I need to do on my end? I haven't used github before.

**Comment by BRLWK** [comment]
In your repo sounds good. I think I messed up the file locations, is there anything I need to do on my end? I haven't used github before.

**Comment by perkinslr** [comment]
> In your repo sounds good. I think I messed up the file locations, is there anything I need to do on my end? I haven't used github before.

Probably best thing to do is ask Sam or N7 or one of the other xml-people on our discord.  Or when you are ready to try again, we can ping N7 to come help here.

**Pull request closed without merging**
