### PR TITLE
Add Textiles+ mod compatibility and make Fernir leather from VFE-Vikings count as soft armor type

### PR DESCRIPTION
**Pull request by AKEKHQ**
## Additions

Textiles+ compatiblitiy adding things like Linnen cloth alternative, Denim slightily better fabric made from cloth and more, as well as Kevlar, hard to make but really strong material and Sinstrand improved devilstrand with high fire protection, both kevlar and sinstrand counting as soft armor

## Changes

Changed code of VFE-Vikings added Fernir leather soo it counts as soft armor, as its suposed to be stronger but less preety version of thrumbofur

Adjusted armor value of the animals added by VFE-Vikings to stay consistent with their vanilla values in comparison to CE values

## Reasoning

I wanted to implement more fabrics to choose from while using soft armor vests, and more high end craftable materials that arent hyperweave, as well as more uses for cloth than medicine, weak clothes you wanna replace asap, and rugs, and since this mod adds preety much all of this i decided to add compatibility since i almost allways use CE. And Fernnir leather just made sense for what it is soo i added it

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

### CODE REVIEW

**Comment by ItsSamGray** [comment]
Since Devilstrand is our Kevlar equivalent in CE, you might want to tone the Kevlar and Sinstrand's armor ratings down to how Devilstrand is set up i.e. 0.5mm sharp and 0.1MPa blunt armor. The rest of the patch looks good to me.

**Comment by AKEKHQ** [comment]
The thing is, that kevlar and sinstrand are made from Devilstrand at loss ssince kevalr costs 20 devilstrand and 20 synthread and Sinstrand costs 15 devilstrand and 30 cloth, they are suposed to be stronger than devilstrand, at a cost extra resourses, work and tech cost

**Comment by ItsSamGray** [comment]
> The thing is, that kevlar and sinstrand are made from Devilstrand at loss ssince kevalr costs 20 devilstrand and 20 synthread and Sinstrand costs 15 devilstrand and 30 cloth, they are suposed to be stronger than devilstrand, at a cost extra resourses, work and tech cost

Yea... the problem is that even the vanilla values for those materials are overtuned as well, Devilstrand is already Kevlar in CE... we might be able the tweak the recipes to adjust for that.

**Comment by ItsSamGray** [comment]
Will open another PR with these changes because i don't have push access to the repo of the author to fix the folder names.

**Pull request closed without merging**
