### PR TITLE
Dragons Descent update

### LINKED ISSUE #1657: [Patch Request]: Dragon's Descent Update
**Mod name:**
Dragon's Descent
**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=2026992161
**Description:**
Provide a brief overview of what content the mod adds or modifies. Specify what content in particular you believe require a patch to be compatibly with Combat Extended.

Dragon's Descent's 1.3 update changes and adds new defs from 1.2 update. So far ability defs have been changed, damage defs have been changed, projectile defs have been changed (new def using vfecore), ThingDef_Items have been changed, new race tools have been added to the dragons, there is a new drug (bulk), and weapons and apparel have been added.

TL:DR
Dragon's Descent's 1.3 update changes a lot more than what the recent patch commit solves.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

### PR DESCRIPTION
**Pull request by feeddanoob**
## Additions
New Weapons, Armor, DamageDefs, and Materials

## Changes
Changed the DragonRace (both restructured and balanced to what the Dragon Descent author had in mind for power). Renamed a few files to match Dragon Descents Files. Commented out the AbilityDefs since I do not think they are used. Commented out the wildness changes and manhunter changes, I think the original Defs do a good job for wildness and manhunter changes seem out of scope for CE.

## References

- Closes #1657 

## Reasoning

I tried referencing the weapons and armors/apparel to either vanilla counterparts or other similar defs from patched mods as well as trying to use the spreadsheet for balance. Since this is a fantasy mod balance is going to be ruff for vanilla rim.
Created a new projectile to remove the animated fire breath in DD 1.3 update.

## Testing

Check tests you have performed:
- [x] Compiles without warnings on game startup 
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (1 hour)

(I will try to test if the fire breath and weapons/armors causes issues).

### CODE REVIEW

**Comment by feeddanoob** [comment]
Draft for now so I can playtest in game for a bit to see if errors or unintended features crop up.

**Comment by feeddanoob** [comment]
Need help for the balancing aspect.

**Comment by feeddanoob** [comment]
Not sure if the fire breath should be explosive or a bullet...

**Comment by feeddanoob** [comment]
Okay I think everything works as intended with no errors in game.

**Review by ItsSamGray — APPROVED** [review]

**Review by ItsSamGray — APPROVED** [review]

**Pull request merged**
